<html>
<head>
		<title>xPL Alarm System</title>
		<link href="/mchp.css" rel="stylesheet" type="text/css" />
	</head>

	<body>
		<div id="shadow-one">
		<div id="shadow-two">
		<div id="shadow-three">
		<div id="shadow-four">
		<div id="page">

		<h2>HA Alarm System</h2>

		<div id="title">
			<div class="right">Control Panel </div>
			<span id="hello">&nbsp;</span>
		</div>

		<div id="menu">
			<a href="/index.htm">System Status</a>
			<a href="/admin/ipconfig.htm">IP Configuration</a>
			<a href="/admin/zoneconfig.htm">Zone Configuration</a>
			<a href="/admin/areaconfig.htm">Area Configuration</a>
			<a href="/admin/alarmconfig.htm">Alarm Configuration</a>
			<a href="/admin/users.htm">User Admin</a>
			<a href="/control.htm">Alarm Control</a>
			<a href="/email/index.htm">Email Options</a>
			<a href="/admin/firmware.htm">Firmware</a>
		</div>

		<div id="content">