Alarm Cabinent: PIC Code/AES.h File Reference
PIC Code/AES.h File Reference
Defines
#define calcKey
#define DECODE
Functions
void AESDecode (unsigned char *block, unsigned char *key)
void AESCalcDecodeKey (unsigned char *key)
Define Documentation
#define calcKey
Definition at line 5 of file AES.h.
#define DECODE
Definition at line 6 of file AES.h.
Function Documentation
void AESCalcDecodeKey (unsigned char * key)
Definition at line 432 of file AES.c.
References _rcon, _roundCounter, and EncKeySchedule().
Referenced by xPLAuthenticate().
{
        _roundCounter = 10;
        _rcon=0x01;
        do
        {
                EncKeySchedule(key);
                _roundCounter--;
        }
        while(_roundCounter>0);
}
void AESDecode (unsigned char * block, unsigned char * key)
Definition at line 464 of file AES.c.
References _rcon, _roundCounter, BLOCKSIZE, DecKeySchedule(), DecodeShiftRow(), SiTable, x1, x2, and x3.
Referenced by xPLAuthenticate().
{
        unsigned char i;
        unsigned char b[BLOCKSIZE];
        /* reconstruct key */
        i=1;
        _rcon = 0x36;
        /* initiate round counter = 10 */
        _roundCounter = 10;
        /* key addition */
        for(i=0;i<BLOCKSIZE;i++)
        {
                block[i] ^= key[i];
        }
        Nop();
        do
        {
                if( _roundCounter != 10)
                {
                        /* inverse mix column */
                        /*     mix column */
{
                                unsigned char temp0,temp1,temp2,temp3;
                                for(i=0;i<16;i+=4)
{
                                        temp3=x3[block[i+0x00]]^x3[block[i+0x01]]^x3[block[i+0x02]]^x3[block[i+0x03]]^block[i+0x00]^block[i+0x01]^block[i+0x02]^block[i+0x03];
                                        temp0=x2[block[i+0x00]]^x1[block[i+0x00]]
                                                          ^x1[block[i+0x01]]
                                                          ^x2[block[i+0x02]]
                                                          ^temp3^block[i+0x00];
                                        temp1=x2[block[i+0x01]]^x1[block[i+0x01]]
                                                          ^x1[block[i+0x02]]
                                                          ^x2[block[i+0x03]]
                                                          ^temp3^block[i+0x01];
                                        temp2=x2[block[i+0x02]]^x1[block[i+0x02]]
                                                          ^x1[block[i+0x03]]
                                                          ^x2[block[i+0x00]]
                                                          ^temp3^block[i+0x02];
                                        temp3^=x2[block[i+0x03]]^x1[block[i+0x03]]
                                                          ^x1[block[i+0x00]]
                                                          ^x2[block[i+0x01]]
                                                          ^block[i+0x03];
                                        block[i+0]=temp0;
                                        block[i+1]=temp1;
                                        block[i+2]=temp2;
                                        block[i+3]=temp3;
                                }
                        }
                }
                /* s table substitution */
                for(i=0;i<BLOCKSIZE;i++)
                {
                        block[i]=SiTable[block[i]];
                }
                /* decode shift row */
                DecodeShiftRow(block);
                /* decode key schedule */
                DecKeySchedule(key);
                for(i=0;i<BLOCKSIZE;i++)
                {
                        block[i] ^= key[i];
                }
                _roundCounter--;
        }
        while( _roundCounter !=0);
}