Alarm Cabinent: PIC Code/SecuritySystem.c File Reference
PIC Code/SecuritySystem.c File Reference
Main of security.
#include "TCPIP Stack/TCPIP.h"
#include "xPL.h"
#include "SecuritySystem.h"
Typedefs
typedef enum _SecurityCommands SecurityCommands
Types of security commands received.
typedef enum _SecurityRequests SecurityRequests
Types of security requests received.
Enumerations
enum _SecurityCommands {
Command_arm = 0, Command_armhome, Command_armaway, Command_armlatchkey,
Command_disarm, Command_panic, Command_isolate, Command_bypass,
Command_enable
}
Types of security commands received.
enum _SecurityRequests {
Request_gateinfo = 0, Request_zonelist, Request_arealist, Request_zoneinfo,
Request_areainfo, Request_gatestat, Request_zonestat, Request_areastat
}
Types of security requests received.
Functions
static void LoadDefaultConfig (void)
static BOOL IOTasks (void)
static void StateChangeToArmFailed (void)
static void StateChangeToArm (BOOL isLatchKey)
static void TaskAlarmed (void)
static void TaskAlarming (void)
static void StateChangeToAlarmed (void)
static void StateChangeToAlarming (int ZoneID)
static Zone_States ArmingZoneState (int TheZone)
BOOL SchemaInit (void)
void xPLFactoryRestart (void)
BOOL SchemaTasks (void)
void ClearArmingFlags (void)
void Arm (int short TimeDelay)
void ArmHome (int short TimeDelay)
void ArmAway (int short TimeDelay)
void ArmLatchkey (int short TimeDelay)
void Panic (void)
BOOL isZoneMemberOfArea (int TheZone, int TheArea)
void SetArmingArea (char *TheValue)
void SetArming (char *TheValue, BOOL isZone)
void SchemaProcessUDPMsg (void)
void Disarm (void)
void IsolateZone (int TheZone)
void IsolateArea (int TheArea)
void bypassZone (int TheZone)
void bypassArea (int TheArea)
void EnableZone (int TheZone)
void EnableArea (int TheArea)
Variables
Alarm_States AlarmState
Reflects the state of the alarm.
Alarm_States PreviousAlarmState
The previous state of the alarm system, used when state change fails.
TICK EntryTimer
Zone Entery timer.
TICK TriggeredEntryZone
Triggered Entery Zone that set off the timer.
TICK ExitTimer
Exit timer - 0 means off.
TICK NextZoneCheckDelay
Delay used so we are not always checking the status of the zones.
TICK AlarmingTimer
Times how long the alarm will sound for.
TICK SirenTimer
Times the delay before acivating the external siren.
TICK BatteryCheckTimer = 0
Timer checking the battery status.
int iCount
Counters that are used in a number of places, centraly defined to reduce memory use.
int i2Count
char UserID [USERNAMELENGTH]
Name of user.
unsigned int LastZoneAlarmed
The last zone to change to alarmed state. used in SMTP.c.
ROM char * AlarmTypesText []
determines the text outputed in the xPL message for each of the alarm types
ROM char * ZoneTypesText []
determines the text outputed in the xpl message for each of the zone types
static ROM char * SecurityCommandText []
Security command Types.
static ROM char * SecurityRequestsText []
xPL feild values for the different security requests
DWORD dwLastUpdateTick
Tick count of last update.
xPLTaskLists xPLTaskList
The Task buffer for sending xPL messages.
xPLConfigs xPLConfig
Configuration entries.
ZoneConfigs ZoneConfig [ZONECOUNT]
Stores each Zones configuration information.
AreaConfigs AreaConfig [AREACOUNT]
Stores each Area configuration information.
Detailed Description
Main of security.
Definition in file SecuritySystem.c.
Typedef Documentation
typedef enum _SecurityCommands SecurityCommands
Types of security commands received.
typedef enum _SecurityRequests SecurityRequests
Types of security requests received.
Enumeration Type Documentation
enum _SecurityCommands
Types of security commands received.
Enumerator:
Command_arm
Command_armhome
Command_armaway
Command_armlatchkey
Command_disarm
Command_panic
Command_isolate
Command_bypass
Command_enable
Definition at line 82 of file SecuritySystem.c.
{
        Command_arm = 0,
        Command_armhome,
        Command_armaway,
        Command_armlatchkey,
        Command_disarm,
        Command_panic,
        Command_isolate,
        Command_bypass,
        Command_enable
} SecurityCommands;
enum _SecurityRequests
Types of security requests received.
Enumerator:
Request_gateinfo
Request_zonelist
Request_arealist
Request_zoneinfo
Request_areainfo
Request_gatestat
Request_zonestat
Request_areastat
Definition at line 96 of file SecuritySystem.c.
{
        Request_gateinfo = 0,
        Request_zonelist,
        Request_arealist,
        Request_zoneinfo,
        Request_areainfo,
        Request_gatestat,
        Request_zonestat,
        Request_areastat
} SecurityRequests;
Function Documentation
void Arm (int short TimeDelay)
Function Arm PreCondition: Arming flags must be set Side Effects: Arm device Overview: Changes that alarm state to Arm based on the arming flags
Parameters:
exit delay
Returns:
None
Definition at line 1122 of file SecuritySystem.c.
References addxPLMessage(), AREACOUNT, xPLTasks::ErrorMessage, ExitTimer, FALSE, i2Count, iCount, putrsUART, StateChangeToArm(), xPLTaskLists::Task, TB_SendError, TRUE, and ZONECOUNT.
Referenced by SchemaProcessUDPMsg().
{
        int Counter;
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Arm\r\n");
#endif
        // Check for a zone list or area list, if missing send error with description of fault
        for (iCount = 0, i2Count = 0; iCount < AREACOUNT; iCount++) {
                if (AreaConfig[iCount].IsChangeFlagged == TRUE)
                        i2Count++;
        } //for
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                if (ZoneConfig[iCount].IsChangeFlagged == TRUE)
                        i2Count++;
        } //for
        if (i2Count == 0) {
                i2Count = addxPLMessage (TB_SendError);
                xPLTaskList.Task[i2Count].ErrorMessage = "Nothing selected to arm";
        }
        else
                ExitTimer = TickGet() + (TimeDelay * TICK_SECOND);
        StateChangeToArm (FALSE);
} // Arm
void ArmAway (int short TimeDelay)
Function ArmAway PreCondition: None Side Effects: Arm device Overview: Changes that alarm state to Arm Away
Parameters:
exit delay
Returns:
None
Definition at line 1192 of file SecuritySystem.c.
References ExitTimer, FALSE, iCount, ZoneConfigs::IsChangeFlagged, putrsUART, StateChangeToArm(), TRUE, and ZONECOUNT.
Referenced by HTTPExecuteGet(), and SchemaProcessUDPMsg().
{
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"ArmAway\r\n");
#endif
        // Set arming flags on all zones
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsChangeFlagged = TRUE;
        }
        ExitTimer = TickGet() + (TimeDelay * TICK_SECOND);
        StateChangeToArm (FALSE);
} //ArmAway
void ArmHome (int short TimeDelay)
Function ArmHome PreCondition: None Side Effects: Arm device Overview: Changes that alarm state to Arm Home
Parameters:
exit delay
Returns:
None
Definition at line 1162 of file SecuritySystem.c.
References ExitTimer, FALSE, iCount, Interior, ZoneConfigs::IsChangeFlagged, Perimiter, putrsUART, StateChangeToArm(), TRUE, and ZONECOUNT.
Referenced by HTTPExecuteGet(), and SchemaProcessUDPMsg().
{
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"ArmHome\r\n");
#endif
        // Set arming flags on all zones of type perimeter
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                if (ZoneConfig[iCount].ZoneType == Perimiter) ZoneConfig[iCount].IsChangeFlagged = TRUE;
                if (ZoneConfig[iCount].ZoneType == Interior) ZoneConfig[iCount].IsChangeFlagged = FALSE;
        }
        ExitTimer = TickGet() + (TimeDelay * TICK_SECOND);
        StateChangeToArm(FALSE);
} // ArmHome
Zone_States ArmingZoneState (int TheZone) [static]
Function ArmingZoneState PreCondition: Arming flags set Side Effects: Overview: StateNormal means everything is ok and the zone is in a good state for arming.
Parameters:
The zone to be checked
Returns:
Zone_States, state of the zone
Definition at line 1607 of file SecuritySystem.c.
References StateNormal, StateTamper, and StateTrigger.
Referenced by StateChangeToArm().
{
        // zone is not marked as arming
        if (!ZoneConfig[TheZone].IsChangeFlagged)
                return StateNormal;
        // isolated or bypassed
        if ((ZoneConfig[TheZone].IsBypassed) || (ZoneConfig[TheZone].IsIsolated))
                return StateNormal;
        // Triggered zone is not an entry point
        if ((ZoneConfig[TheZone].IsTriggered) && (!ZoneConfig[TheZone].IsEntry))
                return StateTrigger;
        // Anything that is tampered is a no no
        if (ZoneConfig[TheZone].IsTampered)
                return StateTamper;
        // If we get this far then all is good.
        return StateNormal;
}
void ArmLatchkey (int short TimeDelay)
Function ArmLatchkey PreCondition: None Side Effects: Arm device Overview: Changes that alarm state to latch Key
Parameters:
exit delay
Returns:
None
Definition at line 1220 of file SecuritySystem.c.
References ExitTimer, iCount, ZoneConfigs::IsChangeFlagged, putrsUART, StateChangeToArm(), TRUE, and ZONECOUNT.
Referenced by HTTPExecuteGet(), and SchemaProcessUDPMsg().
{
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"ArmLatchkey\r\n");
#endif
        // Set arming flags on all zones
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsChangeFlagged = TRUE;
        }
        ExitTimer = TickGet() + (TimeDelay * TICK_SECOND);
        StateChangeToArm (TRUE);
} // ArmLatchkey
void bypassArea (int TheArea)
Function bypassArea PreCondition: None Side Effects: bypass flag Overview: will set the bypass flag for the area provided also sets the flag for any zones that are related
Parameters:
Area ID
Returns:
None
Definition at line 2162 of file SecuritySystem.c.
References Class_Security, EEDATASTART_AREA, EEDATASTART_ZONE, FALSE, iCount, AreaConfigs::IsAlarmed, ZoneConfigs::IsBypassed, AreaConfigs::IsBypassed, AreaConfigs::IsChangeFlagged, AreaConfigs::IsTampered, AreaConfigs::IsTriggered, isZoneMemberOfArea(), putrsUART, TRUE, Type_Zone, xPL_STATUS, xPLSaveEEConfig(), XPLSendHeader(), XPLSocket, and ZONECOUNT.
{
        int short iCount;
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Bypass Area\r\n");
#endif
        //Set the area's bypass flag to true
        AreaConfig[TheArea].IsBypassed = TRUE;
        AreaConfig[TheArea].IsChangeFlagged = FALSE;
        // clear out the status flags
        AreaConfig[TheArea].IsTampered = FALSE;
        AreaConfig[TheArea].IsTriggered = FALSE;
        AreaConfig[TheArea].IsAlarmed = FALSE;
        //Send message
        //Check if we have a MAC transmit port, if not then shit yourself
        if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"#ERROR# bypassZone, no MAC transmit port\r\n");
#endif
        }
        else {
                // Generate xPL head with type security.zone
                XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Zone);
                UDPPutROMString((ROM BYTE*) "area=");
                UDPPut('0'+TheArea);
                UDPPutROMString((ROM BYTE*) "\nbypassed=true\n}\n");
                UDPFlush();
        }//UDPIsPutReady(XPLSocket)
        //cycle through all zones and set their bypass flag to true if they are a member
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                if (isZoneMemberOfArea(iCount, TheArea) == TRUE) {
                        ZoneConfig[iCount].IsBypassed = TRUE;
                }// ZoneConfig
        }// for iCount
        //now save the changes
        xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
        xPLSaveEEConfig(AreaConfig, EEDATASTART_AREA, sizeof(AreaConfig));
} // bypassArea
void bypassZone (int TheZone)
Function bypassZone PreCondition: None Side Effects: bypass flag Overview: will set the bypass flag for the zone provided
Parameters:
Zone ID
Returns:
None
Definition at line 2108 of file SecuritySystem.c.
References ZoneConfigs::BounceDelay, Class_Security, EEDATASTART_ZONE, FALSE, ZoneConfigs::IsAlarmed, ZoneConfigs::IsBypassed, ZoneConfigs::IsChangeFlagged, ZoneConfigs::IsTampered, ZoneConfigs::IsTriggered, putrsUART, TRUE, Type_Zone, xPL_STATUS, xPLMsgKey, xPLSaveEEConfig(), XPLSendHeader(), and XPLSocket.
Referenced by SchemaTasks().
{
        // say hello
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Bypass Zone\r\n");
#endif
        //Set the zone's bypass flag to true
        ZoneConfig[TheZone].IsBypassed = TRUE;
        ZoneConfig[TheZone].IsChangeFlagged = FALSE;
        // clear out the status flags
        ZoneConfig[TheZone].IsTampered = FALSE;
        ZoneConfig[TheZone].IsTriggered = FALSE;
        ZoneConfig[TheZone].BounceDelay = 0;
        ZoneConfig[TheZone].IsAlarmed = FALSE;
        //Send message
        //Check if we have a MAC transmit port, if not then shit yourself
        if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"#ERROR# bypassZone, no MAC transmit port\r\n");
#endif
        }
        else {
                // Generate xPL head with type security.zone
                XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Zone);
                UDPPutROMString((ROM BYTE*) "event=bypassed\nzone=");
                itoa(TheZone, xPLMsgKey);
                UDPPutArray(xPLMsgKey,strlen(xPLMsgKey));
                UDPPutROMString((ROM BYTE*) "\nstate=true\n}\n");
                UDPFlush();
        }//UDPIsPutReady(XPLSocket)
        //now save the changes
        xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
} // bypassZone
void ClearArmingFlags (void)
Function ClearArmingFlags PreCondition: None Side Effects: Arming flags Overview: utility used to remove all of the arming flags
Parameters:
None
Returns:
None
Definition at line 1091 of file SecuritySystem.c.
References AREACOUNT, FALSE, iCount, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsChangeFlagged, and ZONECOUNT.
Referenced by addxPLMessage(), HTTPExecuteGet(), and SchemaProcessUDPMsg().
{
        //Cycle through all zones and clear arming flags
        for (iCount =0; iCount > ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsChangeFlagged = FALSE;
        }
        //Cycle through all areas and clear arming flags
        for (iCount =0; iCount < AREACOUNT; iCount++) {
                AreaConfig[iCount].IsChangeFlagged = FALSE;
        }
}
void Disarm (void)
Function Disarm PreCondition: UserID must be populated first from Authenticate.c Side Effects: armed flags, state and IO Overview: Disarm the alarm. Uses the UserID to determine who the user was
Parameters:
None
Returns:
None
Definition at line 1938 of file SecuritySystem.c.
References addxPLMessage(), AlarmState, AREACOUNT, Disarmed, EntryTimer, ExitTimer, EXT_SIREN_IO, FALSE, iCount, INT_SIREN_IO, AreaConfigs::IsAlarmed, ZoneConfigs::IsAlarmed, AreaConfigs::IsArmed, ZoneConfigs::IsArmed, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsChangeFlagged, AreaConfigs::IsIsolated, ZoneConfigs::IsIsolated, PreviousAlarmState, putrsUART, STROBE_IO, TB_SendDisarm, and ZONECOUNT.
Referenced by HTTPExecuteGet(), and SchemaProcessUDPMsg().
                   {
        //Ensure entry and exit timers are cleared
        EntryTimer = 0;
        ExitTimer = 0;
        //Change any of the IO lines for sirens and strobe
        STROBE_IO = 0;
        INT_SIREN_IO = 0;
        EXT_SIREN_IO = 0;
        //Change the state to disarmed
        PreviousAlarmState = Disarmed;
        //set the previous state to disarmed as well
        AlarmState = Disarmed;
        //Cycle though all of the zones clear any  Armed, Alarmed, Arming, isolated flags
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsIsolated = FALSE;
                ZoneConfig[iCount].IsArmed = FALSE;
                ZoneConfig[iCount].IsAlarmed = FALSE;
                ZoneConfig[iCount].IsChangeFlagged = FALSE;
        }// for iCount
        //cycle thought all areas clear any Armed, Alarmed, isolated flags
        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                AreaConfig[iCount].IsIsolated = FALSE;
                AreaConfig[iCount].IsArmed = FALSE;
                AreaConfig[iCount].IsAlarmed = FALSE;
                AreaConfig[iCount].IsChangeFlagged = FALSE;
        }// for iCount
        //Send disarmed message
        addxPLMessage (TB_SendDisarm);
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"State change to disarm\r\n");
#endif
} // Disarm
void EnableArea (int TheArea)
Function EnableArea PreCondition: None Side Effects: bypass, isolated flag Overview: will set the bypass flag for the area provided also sets the flag for any zones that are related
Parameters:
Area ID
Returns:
None
Definition at line 2311 of file SecuritySystem.c.
References Class_Security, EEDATASTART_AREA, EEDATASTART_ZONE, FALSE, iCount, ZoneConfigs::IsBypassed, AreaConfigs::IsBypassed, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsIsolated, AreaConfigs::IsIsolated, isZoneMemberOfArea(), putrsUART, TRUE, Type_Area, xPL_STATUS, xPLSaveEEConfig(), XPLSendHeader(), XPLSocket, and ZONECOUNT.
{
        // It can be isolated and bypassed at the same time.
        // If the area is bypassed send
        // security.area
        // { event=bypassed
        // area=id
        // state=false }
        // clear the bypassed flag
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Enable Area\r\n");
#endif
        AreaConfig[TheArea].IsChangeFlagged = FALSE;
        if (AreaConfig[TheArea].IsBypassed) {
                //Check if we have a MAC transmit port, if not then shit yourself
                if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                        putrsUART((ROM char*)"#ERROR# EnableArea, no MAC transmit port\r\n");
#endif
                }
                else {
                        // Generate xPL head with type security.zone
                        XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Area);
                        UDPPutROMString((ROM BYTE*) "area=");
                        UDPPut('0'+ TheArea);
                        UDPPutROMString((ROM BYTE*) "\nbypassed=false\n}\n");
                        UDPFlush();
                }//UDPIsPutReady(XPLSocket)
                AreaConfig[TheArea].IsBypassed = FALSE;
                // cycle through all zones and set their flags to true clear if they are a member of this area
                for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                        if (isZoneMemberOfArea(iCount, TheArea)) {
                                ZoneConfig[iCount].IsBypassed = FALSE;
                        }// ZoneConfig
                }// for iCount
        } // IsBypassed
        // if area is isolated then send
        // security.area
        // { event=isolated
        // area=id
        // state=false }
        // clear the isolated flag
        if (AreaConfig[TheArea].IsIsolated) {
                //Check if we have a MAC transmit port, if not then shit yourself
                if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                        putrsUART((ROM char*)"#ERROR# EnableArea, no MAC transmit port\r\n");
#endif
                }
                else {
                        // Generate xPL head with type security.zone
                        XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Area);
                        UDPPutROMString((ROM BYTE*) "area=");
                        UDPPut('0'+TheArea);
                        UDPPutROMString((ROM BYTE*) "\nisolated=false\n}\n");
                        UDPFlush();
                }//UDPIsPutReady(XPLSocket)
                AreaConfig[TheArea].IsIsolated = FALSE;
                // cycle through all zones and set their flags to true clear if they are a member of this area
                for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                        if (isZoneMemberOfArea(iCount, TheArea) == TRUE) {
                                ZoneConfig[iCount].IsIsolated = FALSE;
                        }// ZoneConfig
                }// for iCount
        } // IsIsolated
        //now save the changes
        xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
        xPLSaveEEConfig(AreaConfig, EEDATASTART_AREA, sizeof(AreaConfig));
}
void EnableZone (int TheZone)
Function EnableZone PreCondition: None Side Effects: bypass, isolated and arming flags Overview: will clear the bypass, isolated and arming flag for the zone provided Should only be called as a task. Can take 2 runs to complete task
Parameters:
Zone ID
Returns:
None
Definition at line 2226 of file SecuritySystem.c.
References Class_Security, EEDATASTART_ZONE, FALSE, ZoneConfigs::IsBypassed, ZoneConfigs::IsChangeFlagged, ZoneConfigs::IsIsolated, putrsUART, TRUE, Type_Zone, xPL_STATUS, xPLMsgKey, xPLSaveEEConfig(), XPLSendHeader(), and XPLSocket.
Referenced by SchemaTasks().
{
        // It can be isolated and bypassed at the same time.
        // If the zone is bypassed send
        // security.zone
        //  event=bypassed
        // area=id
        // state=false
        // clear the bypassed flag
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Enabling Zone\r\n");
#endif
        if (ZoneConfig[TheZone].IsBypassed) {
                //Check if we have a MAC transmit port, if not then shit yourself
                if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                        putrsUART((ROM char*)"#ERROR# EnableZone, no MAC transmit port\r\n");
#endif
                }
                else {
                        // Generate xPL head with type security.zone
                        XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Zone);
                        UDPPutROMString((ROM BYTE*) "event=bypassed\nzone=");
                        itoa(TheZone, xPLMsgKey);
                        UDPPutArray(xPLMsgKey,strlen(xPLMsgKey));
                        UDPPutROMString((ROM BYTE*) "\nstate=false\n}\n");
                        UDPFlush();
                }//UDPIsPutReady(XPLSocket)
                ZoneConfig[TheZone].IsBypassed = FALSE;
                // return back after a TCIP stack task run has occured to complete the Isolated message
                if (ZoneConfig[TheZone].IsIsolated == FALSE) ZoneConfig[TheZone].IsChangeFlagged = FALSE;
        } // IsBypassed
        else if (ZoneConfig[TheZone].IsIsolated) {
                //Check if we have a MAC transmit port, if not then shit yourself
                if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                        putrsUART((ROM char*)"#ERROR# EnableZone, no MAC transmit port\r\n");
#endif
                }
                else {
                        // Generate xPL head with type security.zone
                        XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Zone);
                        UDPPutROMString((ROM BYTE*) "event=isolated\nzone=");
                        uitoa(TheZone, xPLMsgKey);
                        UDPPutArray(xPLMsgKey,strlen(xPLMsgKey));
                        UDPPutROMString((ROM BYTE*) "\nstate=false\n}\n");
                        UDPFlush();
                }//UDPIsPutReady(XPLSocket)
                ZoneConfig[TheZone].IsIsolated = FALSE;
                ZoneConfig[TheZone].IsChangeFlagged = FALSE;
                //now save the changes
                xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
        } // IsIsolated
} //EnableZone
BOOL IOTasks (void) [static]
Function IOTasks PreCondition: None Side Effects: Zone and Area states, sends UDP Overview: This procedure moniters the statis of zones and areas, sending triggers or alarms of a state changes It also calls the functions that control the current alarm state (alarming / alarmed)
Todo:
when exiting from sending a message need to return to next position. Low task
Returns:
BOOL, no UDP message sent (false means message sent)
Definition at line 780 of file SecuritySystem.c.
References addxPLMessage(), Alarmed, Alarmed24, Alarming, Alarming24, AlarmState, Disarmed, xPLConfigs::EntryDelay, EntryTimer, ExitTimer, FALSE, IsZoneTriggered(), xPLTasks::NewZoneState, NextZoneCheckDelay, SendZoneStateMsg(), StateChangeToAlarming(), StateNormal, StateNothing, StateTamper, StateTrigger, xPLTaskLists::Task, TaskAlarmed(), TaskAlarming(), TB_SendAreaStateMsg, TriggeredEntryZone, TRUE, TwentyFourHour, ZONECHECKDELAY, and ZONECOUNT.
Referenced by SchemaTasks().
                    {
        int CheckingZone, xPLTaskID;
        Zone_States ZoneResult, PreviousZoneState;
        //If EntryTimer set and state is Disarmed, clear entry timer
        if ((EntryTimer != (unsigned)0) && (AlarmState == Disarmed)) EntryTimer = 0;
        //If entry timer has expired then Change to Alarming and sent ZoneID of the zone that triggered the entry timer
        if ((TickGet() > EntryTimer) && (EntryTimer != (unsigned)0) )   {
                StateChangeToAlarming(TriggeredEntryZone);
                return FALSE;
        }
        //Loop though all Zones's only when needed to
        if (TickGet() > NextZoneCheckDelay) {
                for (CheckingZone = 0; CheckingZone < ZONECOUNT; CheckingZone++) {
                        // What is the previous state
                        if (ZoneConfig[CheckingZone].IsTampered) PreviousZoneState = StateTamper;
                        else if (ZoneConfig[CheckingZone].IsTriggered) PreviousZoneState = StateTrigger;
                        else PreviousZoneState = StateNormal;
                        // determine the current state
                        ZoneResult = IsZoneTriggered(CheckingZone);
                        //If the result is nothing then do nothing
                        if (ZoneResult == StateNothing)
                                goto EndLoop;
                        //If returning from Tamper send ZoneState and AreaState messages
                        if ((ZoneResult == StateNormal) && (PreviousZoneState ==  StateTamper)){
                                SendZoneStateMsg(StateNormal,CheckingZone);
                                xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                xPLTaskList.Task[xPLTaskID].NewZoneState = StateNormal;
                                return FALSE;
                        }
                        //If Tamper send ZoneState and AreaState messages and sound alarm
                        if (ZoneResult == StateTamper) {
                                // set the alarm off when any zone is tampered
                                StateChangeToAlarming(CheckingZone);
                                SendZoneStateMsg(StateTamper,CheckingZone);
                                xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                xPLTaskList.Task[xPLTaskID].NewZoneState = StateTamper;
                                return FALSE;
                        }
                        //If returning from triggered send ZoneState and AreaState messages
                        if ((ZoneResult == StateNormal) && (PreviousZoneState ==  StateTrigger)){
                                SendZoneStateMsg(StateNormal,CheckingZone);
                                xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                xPLTaskList.Task[xPLTaskID].NewZoneState = StateNormal;
                                return FALSE;
                        }
                        //If triggered and 24H, set the alarm off
                        if ((ZoneResult == StateTrigger) && (ZoneConfig[CheckingZone].ZoneType == TwentyFourHour)) {
                                StateChangeToAlarming(CheckingZone);
                                return FALSE;
                        }
                        //If Triggered and not Armed send trigger message
                        if ((ZoneResult == StateTrigger) && (!ZoneConfig[CheckingZone].IsArmed)) {
                                SendZoneStateMsg(StateTrigger,CheckingZone);
                                xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                xPLTaskList.Task[xPLTaskID].NewZoneState = StateTrigger;
                                return FALSE;
                        }
                        //If Triggered and Zone is Armed
                        if ((ZoneResult == StateTrigger) && (ZoneConfig[CheckingZone].IsArmed)) {
                                // If the zone is an entry point and Exit time is not Zero, set (Triggered Entery Zone) = ZoneID and send trigger messages
                                if ((ExitTimer != (unsigned)0) && (ZoneConfig[CheckingZone].IsEntry)) {
                                        SendZoneStateMsg (StateTrigger,CheckingZone);
                                        xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                        xPLTaskList.Task[xPLTaskID].NewZoneState = StateTamper;
                                        return FALSE;
                                }
                                //If the zone is an entry point and the Entry timer is not set, then set it and send trigger messages
                                if ((EntryTimer == (unsigned)0) && (ZoneConfig[CheckingZone].IsEntry)) {
                                        EntryTimer = TickGet() + (TICK_SECOND * xPLConfig.EntryDelay);
                                        TriggeredEntryZone = CheckingZone;
                                        SendZoneStateMsg (StateTrigger,CheckingZone);
                                        xPLTaskID = addxPLMessage (TB_SendAreaStateMsg);
                                        xPLTaskList.Task[xPLTaskID].NewZoneState = StateTrigger;
                                        return FALSE;
                                }
                                //Now we set the alarm off
                                StateChangeToAlarming(CheckingZone);
                                return FALSE;
                        }
                EndLoop:
                        TRUE; // what a funny little hack ;)
                }//Loop ends here
                // Set the time of the next zone check
                NextZoneCheckDelay = TickGet() + (TICK_SECOND / ZONECHECKDELAY);
        } // end of delay
        //If Exit timer active and time passed, then set it to zero.
        if ((ExitTimer !=(unsigned)0) && (TickGet() > ExitTimer)) ExitTimer = 0;
        //If in alarming state, call the alarmed task manager
        if ((AlarmState == Alarming) || ( AlarmState == Alarming24))  TaskAlarming();
        //If in alarmed state call the alarmed task
        if ((AlarmState == Alarmed) || ( AlarmState == Alarmed24))  TaskAlarmed();
        return TRUE;
} //IOTasks
void IsolateArea (int TheArea)
Function IsolateArea PreCondition: None Side Effects: isolated flag Overview: will set the isolated flag for the area provided also sets the flag for any zones that are related
Parameters:
Area ID
Returns:
None
Definition at line 2048 of file SecuritySystem.c.
References Class_Security, EEDATASTART_AREA, EEDATASTART_ZONE, FALSE, iCount, AreaConfigs::IsAlarmed, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsIsolated, AreaConfigs::IsIsolated, AreaConfigs::IsTampered, AreaConfigs::IsTriggered, isZoneMemberOfArea(), putrsUART, TRUE, Type_Area, xPL_STATUS, xPLSaveEEConfig(), XPLSendHeader(), XPLSocket, and ZONECOUNT.
{
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Isolate Area\r\n");
#endif
        //Set the area's isolated flag to true
        AreaConfig[TheArea].IsIsolated = TRUE;
        AreaConfig[TheArea].IsChangeFlagged = FALSE;
        // clear out the status flags
        AreaConfig[TheArea].IsTampered = FALSE;
        AreaConfig[TheArea].IsTriggered = FALSE;
        AreaConfig[TheArea].IsAlarmed = FALSE;
        //Send message
        //Check if we have a MAC transmit port, if not then shit yourself
        if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"#ERROR# IsolateArea, no MAC transmit port\r\n");
#endif
        }
        else {
                // Generate xPL head with type security.zone
                XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Area);
                UDPPutROMString((ROM BYTE*) "area=");
                UDPPut('0'+TheArea);
                UDPPutROMString((ROM BYTE*) "\nisolated=true");
                UDPFlush();
        }//UDPIsPutReady(XPLSocket)
        //cycle through all zones and set their isolated flag to true if they are a member
        for (iCount = 0; iCount <= ZONECOUNT; iCount++) {
                if (isZoneMemberOfArea(iCount, TheArea)) {
                        ZoneConfig[iCount].IsIsolated = TRUE;
                }// ZoneConfig
        }// for iCount
        //now save the changes
        xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
        xPLSaveEEConfig(AreaConfig, EEDATASTART_AREA, sizeof(AreaConfig));
} // IsolateZone
void IsolateZone (int TheZone)
Function IsolateZone PreCondition: None Side Effects: isolated flag Overview: will set the isolated flag for the zone provided
Parameters:
Zone ID
Returns:
None
Definition at line 1995 of file SecuritySystem.c.
References ZoneConfigs::BounceDelay, Class_Security, EEDATASTART_ZONE, FALSE, ZoneConfigs::IsAlarmed, ZoneConfigs::IsChangeFlagged, ZoneConfigs::IsIsolated, ZoneConfigs::IsTampered, ZoneConfigs::IsTriggered, putrsUART, TRUE, Type_Zone, xPL_STATUS, xPLMsgKey, xPLSaveEEConfig(), XPLSendHeader(), and XPLSocket.
Referenced by SchemaTasks().
{
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Isolating zone\r\n");
#endif
        //Set the zone's isolated flag to true
        ZoneConfig[TheZone].IsIsolated = TRUE;
        ZoneConfig[TheZone].IsChangeFlagged = FALSE;
        // clear out the status flags
        ZoneConfig[TheZone].IsTampered = FALSE;
        ZoneConfig[TheZone].IsTriggered = FALSE;
        ZoneConfig[TheZone].BounceDelay = 0;
        ZoneConfig[TheZone].IsAlarmed = FALSE;
        //Send message
        //Check if we have a MAC transmit port, if not then shit yourself
        if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"#ERROR# IsolateZone, no MAC transmit port\r\n");
#endif
        }
        else {
                // Generate xPL head with type security.zone
                XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Zone);
                UDPPutROMString((ROM BYTE*) "event=isolated\nzone=");
                itoa(TheZone, xPLMsgKey);
                UDPPutArray(xPLMsgKey,strlen(xPLMsgKey));
                UDPPutROMString((ROM BYTE*) "\nstate=true\n}\n");
                UDPFlush();
        }//UDPIsPutReady(XPLSocket)
        //now save the changes
        xPLSaveEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig));
} // IsolateZone
BOOL isZoneMemberOfArea (int TheZone, int TheArea)
Function isZoneMemberOfArea PreCondition: None Side Effects: Overview: Returns true of false is an Zone is a member to an area
Parameters:
Zone ID, Area ID
Returns:
BOOL
Definition at line 1467 of file SecuritySystem.c.
References ZoneConfigs::AreaList, FALSE, and TRUE.
Referenced by bypassArea(), EnableArea(), IsolateArea(), IsZoneTriggered(), SendAlarmingMsg(), SendAreaInfo(), SendAreaStat(), SendAreaStateMsg(), SendGateStat(), SendZoneInfo(), StateChangeToAlarming(), and StateChangeToArm().
{
        unsigned short int Result;
#if (AREACOUNT > 8)
#error Having more then 8 areas is not possible under this design.
#endif
        if (TheArea == 0) Result = (ZoneConfig[TheZone].AreaList & 0b00000001);
        if (TheArea == 1) Result = (ZoneConfig[TheZone].AreaList & 0b00000010);
        if (TheArea == 2) Result = (ZoneConfig[TheZone].AreaList & 0b00000100);
        if (TheArea == 3) Result = (ZoneConfig[TheZone].AreaList & 0b00001000);
        if (TheArea == 4) Result = (ZoneConfig[TheZone].AreaList & 0b00010000);
        if (TheArea == 5) Result = (ZoneConfig[TheZone].AreaList & 0b00100000);
        if (TheArea == 6) Result = (ZoneConfig[TheZone].AreaList & 0b01000000);
        if (TheArea == 7) Result = (ZoneConfig[TheZone].AreaList & 0b10000000);
        /*
         #if defined(DEBUG_UART)
         putrsUART((ROM char*)"Is Area Triggered, Area = ");
         putcUART((char) '0' + TheArea);
         putrsUART((ROM char*)" Zone = ");
         uitoa(TheZone, xPLMsgKey);
         putsUART(xPLMsgKey);
         putrsUART((ROM char*)" AreaList = ");
         uitoa(ZoneConfig[TheZone].AreaList, xPLMsgKey);
         putsUART(xPLMsgKey);
         putrsUART((ROM char*)" Result = ");
         uitoa(Result, xPLMsgKey);
         putsUART(xPLMsgKey);
         putrsUART((ROM char*)"\r\n");
         #endif
         */
        if (Result >= 1)  return TRUE;
        else return FALSE;
}//isZoneMemberOfArea
void LoadDefaultConfig (void) [static]
P R I V A T E P R O T O T Y P E S
Function LoadDefaultConfig PreCondition: None Side Effects: Populates ZoneConfig and AreaConfig Overview: Override any values on ZoneConfig and AreaConfig with default values
Parameters:
None
Returns:
None
Definition at line 433 of file SecuritySystem.c.
References xPLConfigs::Alarming24Duration, xPLConfigs::AlarmingDuration, AREACOUNT, ZoneConfigs::AreaList, ZoneConfigs::BounceDelay, Buglary, xPLConfigs::EntryDelay, xPLConfigs::ExitDelay, FALSE, iCount, AreaConfigs::IsAlarmed, ZoneConfigs::IsAlarmed, AreaConfigs::IsArmed, ZoneConfigs::IsArmed, AreaConfigs::IsBypassed, ZoneConfigs::IsBypassed, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsChangeFlagged, ZoneConfigs::IsEntry, AreaConfigs::IsIsolated, ZoneConfigs::IsIsolated, ZoneConfigs::IsNO, AreaConfigs::IsTriggered, ZoneConfigs::IsTriggered, xPLConfigs::NTP_Server, Perimiter, xPLConfigs::SirenDelay, xPLConfigs::SirenDelay24h, xPLConfigs::SMTP_Active, xPLConfigs::SMTP_ArmDisarm, xPLConfigs::SMTP_OnlyInitalAlarm, xPLConfigs::SMTP_Password, xPLConfigs::SMTP_Port, xPLConfigs::SMTP_Server, xPLConfigs::SMTP_To, xPLConfigs::SMTP_User, TRUE, xPLConfigs::Use_AES, AreaConfigs::ZoneAlarmType, ZoneConfigs::ZoneAlarmType, ZONECOUNT, and ZoneConfigs::ZoneType.
Referenced by SchemaInit().
{
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsTriggered = FALSE;
                ZoneConfig[iCount].IsNO = TRUE;
                ZoneConfig[iCount].IsEntry = FALSE;
                ZoneConfig[iCount].IsIsolated = FALSE;
                ZoneConfig[iCount].IsBypassed = FALSE;
                ZoneConfig[iCount].IsArmed = FALSE;
                ZoneConfig[iCount].IsAlarmed = FALSE;
                ZoneConfig[iCount].IsChangeFlagged = FALSE;
                ZoneConfig[iCount].ZoneType = Perimiter;
                ZoneConfig[iCount].ZoneAlarmType = Buglary;
                ZoneConfig[iCount].AreaList = 0;
                ZoneConfig[iCount].BounceDelay = 0;
        } // for
        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                AreaConfig[iCount].IsTriggered = FALSE;
                AreaConfig[iCount].IsTriggered = FALSE;
                AreaConfig[iCount].IsIsolated = FALSE;
                AreaConfig[iCount].IsBypassed = FALSE;
                AreaConfig[iCount].IsArmed = FALSE;
                AreaConfig[iCount].IsAlarmed = FALSE;
                AreaConfig[iCount].IsChangeFlagged = FALSE;
                AreaConfig[iCount].ZoneAlarmType = Buglary;
        } //for
        ZoneConfig[0].AreaList = 0b11111111;
        ZoneConfig[1].AreaList = 0b00000010;
        ZoneConfig[2].AreaList = 0b00000100;
        ZoneConfig[3].AreaList = 0b00001000;
        ZoneConfig[4].AreaList = 0b00010000;
        ZoneConfig[5].AreaList = 0b00100000;
        ZoneConfig[6].AreaList = 0b01000000;
        ZoneConfig[7].AreaList = 0b10000000;
        for (iCount = 6; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsBypassed = TRUE;
        }
        xPLConfig.Alarming24Duration = 18;
        xPLConfig.ExitDelay = 5;
        xPLConfig.EntryDelay = 7;
        xPLConfig.AlarmingDuration = 15;
        xPLConfig.SirenDelay = 10;
        xPLConfig.SirenDelay24h = 12;
        memset(xPLConfig.NTP_Server, '\0',sizeof(xPLConfig.NTP_Server));
        memcpypgm2ram(xPLConfig.NTP_Server, (ROM void*)"pool.ntp.org", 12);
        xPLConfig.Use_AES = FALSE;
        // Email
        memset(xPLConfig.SMTP_Server,'\0', sizeof(xPLConfig.SMTP_Server));
        memset(xPLConfig.SMTP_To,'\0', sizeof(xPLConfig.SMTP_To));
        memset(xPLConfig.SMTP_User,'\0', sizeof(xPLConfig.SMTP_User));
        memset(xPLConfig.SMTP_Password,'\0', sizeof(xPLConfig.SMTP_Password));
        xPLConfig.SMTP_Port = 21;
        //xPLConfig.SMTP_UseSSL = FALSE;
        xPLConfig.SMTP_Active = FALSE;
        xPLConfig.SMTP_ArmDisarm = TRUE;
        xPLConfig.SMTP_OnlyInitalAlarm = TRUE;
} //LoadDefaultConfig
void Panic (void)
Function Panic PreCondition: None Side Effects: IO lines and state Overview: Buts the alarm into the panic state and sends xPL message
Parameters:
None
Returns:
None
Definition at line 1249 of file SecuritySystem.c.
References addxPLMessage(), Alarming, xPLConfigs::AlarmingDuration, AlarmingTimer, AlarmState, EntryTimer, ExitTimer, INT_SIREN_IO, putrsUART, xPLConfigs::SirenDelay, SirenTimer, STROBE_IO, and TB_Panic.
Referenced by HTTPExecuteGet(), and SchemaProcessUDPMsg().
                  {
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"PANIC\r\n");
#endif
        // set off the alarm
        //Ensure entry and exit timers are cleared
        EntryTimer = 0;
        ExitTimer = 0;
        // Start the strobe and internal siren
        STROBE_IO = 1;
        INT_SIREN_IO = 1;
        AlarmState = Alarming;
        SirenTimer = TickGet() + (TICK_SECOND * xPLConfig.SirenDelay); //check to see if external siren should be activated
        AlarmingTimer =  TickGet() + (TICK_SECOND * xPLConfig.AlarmingDuration);
        // Send the alarming message
        addxPLMessage(TB_Panic);
} // Panic
BOOL SchemaInit (void)
Function: SchemaInit PreCondition: UDP initalised, XPL initalised Side Effects: None Overview: General initalisiation procedure for any xPL schema(s). Set inital variables and system state after startup. Assumes TCIP is available and xPL configured. Returns FALSE if the default config options were loaded
Parameters:
None
Returns:
BOOL, is the device configured
Definition at line 193 of file SecuritySystem.c.
References AlarmState, AN2_TRIS, AN3_TRIS, AN4_TRIS, AppConfig, AREACOUNT, Battery_Disconnected, BatteryState, BOOL, ZoneConfigs::BounceDelay, xPLTaskLists::CurentTask, SMTPTaskLists::CurentTask, DEVICEDESCLENGTH, Disarmed, dwLastUpdateTick, EEDATASTART_AREA, EEDATASTART_CONFIG, EEDATASTART_DEVICEDESC, EEDATASTART_MPFS, EEDATASTART_USER, EEDATASTART_XPL, EEDATASTART_ZONE, EntryTimer, ExitTimer, EXT_SIREN_IO, EXT_SIREN_TRIS, FALSE, xPLTaskLists::FreePosition, SMTPTaskLists::FreePosition, xPLTaskLists::GatewayChangedTimer, iCount, INT_SIREN_IO, INT_SIREN_TRIS, AreaConfigs::IsAlarmed, ZoneConfigs::IsAlarmed, AreaConfigs::IsArmed, ZoneConfigs::IsArmed, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsChangeFlagged, AreaConfigs::IsIsolated, ZoneConfigs::IsIsolated, AreaConfigs::IsTampered, ZoneConfigs::IsTampered, AreaConfigs::IsTriggered, ZoneConfigs::IsTriggered, LastZoneAlarmed, LoadDefaultConfig(), NextZoneCheckDelay, NTP_TEST_DONE, NTPTestResponse, PLEXERA_0_IO, PLEXERA_0_TRIS, PLEXERA_1_IO, PLEXERA_1_TRIS, PLEXERA_2_IO, PLEXERA_2_TRIS, PLEXERA_S_TRIS, PreviousAlarmState, putrsUART, putsUART, RejectedPassword, SendGatewayReady(), SLA_CHARGER_IO, SLA_CHARGER_TRIS, SMPTTestResult, xPLConfigs::SMTP_Active, SMTP_Reset, SMTPTaskStack::SMTP_SendType, SMTP_SM_Done, SMTP_SM_InQ, SMTPTaskStack::SMTP_State, SMTP_Test, SMTP_TEST_DONE, SMTPQueueEmail(), SMTPSMSIZE, SMTPTaskList, STROBE_IO, STROBE_TRIS, SUPPLY_ACTIVE_TRIS, SMTPTaskLists::Task, TriggeredEntryZone, TRUE, USERCOUNT, USERNAMELENGTH, USERPASSLENGTH, xPLLoadEEConfig(), ZONECHECKDELAY, and ZONECOUNT.
Referenced by xPLInit().
                       {
        BOOL ReturnResult = TRUE;
        char TempVal[4];
        BYTE * ptr;
        //Load configuration data
        if (xPLLoadEEConfig(ZoneConfig, EEDATASTART_ZONE, sizeof(ZoneConfig)) == FALSE) {
                //EE data incorrect
#if defined(DEBUG_UART)
                putrsUART((ROM char*)" # NOTE# ZoneConfig Loaded default Security Settings\r\n");
#endif
                ReturnResult = FALSE;
        }
        if (xPLLoadEEConfig(&xPLConfig, EEDATASTART_XPL, sizeof(xPLConfig)) == FALSE) {
                //EE data incorrect
#if defined(DEBUG_UART)
                putrsUART((ROM char*)" # NOTE# xPLConfig Loaded default Security Settings\r\n");
#endif
                ReturnResult = FALSE;
        }
        if (xPLLoadEEConfig(AreaConfig, EEDATASTART_AREA, sizeof(AreaConfig)) == FALSE) {
                //EE data incorrect
#if defined(DEBUG_UART)
                putrsUART((ROM char*)" # NOTE# AreaConfig Loaded default Security Settings\r\n");
#endif
                ReturnResult = FALSE;
        }
        if (ReturnResult == FALSE) LoadDefaultConfig();
#if defined(DEBUG_UART)
        ultoa ((unsigned int) sizeof(AppConfig), TempVal);
        putrsUART((ROM char*)"IP AppConfig  size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_CONFIG, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_XPL - (unsigned int)EEDATASTART_CONFIG, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        ultoa ((unsigned int) sizeof(xPLConfig), TempVal);
        putrsUART((ROM char*)"Security Schema xPLConfig size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_XPL, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_ZONE - (unsigned int)EEDATASTART_XPL, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        ultoa ((unsigned int) sizeof(ZoneConfig), TempVal);
        putrsUART((ROM char*)"Security Schema ZoneConfig size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_ZONE, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_AREA - (unsigned int)EEDATASTART_ZONE, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        ultoa ((unsigned int) sizeof(AreaConfig), TempVal);
        putrsUART((ROM char*)"Security Schema AreaConfig size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_AREA, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_USER - (unsigned int)EEDATASTART_AREA, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        ultoa ((unsigned int) USERCOUNT * (USERNAMELENGTH + USERPASSLENGTH) , TempVal);
        putrsUART((ROM char*)"User size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_USER, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_DEVICEDESC - (unsigned int)EEDATASTART_USER, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        ultoa ((unsigned int) DEVICEDESCLENGTH * (ZONECOUNT + AREACOUNT) , TempVal);
        putrsUART((ROM char*)"Device desc size: ");
        putsUART(TempVal);
        putrsUART((ROM char*)" EEStarts:");
        ultoa ((unsigned int) EEDATASTART_DEVICEDESC, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)" EESize: ");
        ultoa ((unsigned int) EEDATASTART_MPFS - (unsigned int)EEDATASTART_DEVICEDESC, TempVal);
        putsUART(TempVal);
        putrsUART((ROM char*)"\r\n");
        //EEDATASTART_MPFS
#endif
        //Clear timers
        EntryTimer = 0;
        TriggeredEntryZone = 0;
        ExitTimer = 0;
        NextZoneCheckDelay = TickGet() + (TICK_SECOND / ZONECHECKDELAY);
        xPLTaskList.GatewayChangedTimer = 0;
        dwLastUpdateTick =0;
        //Set initial alarm state, arming delay and previous arm state
        AlarmState = Disarmed;
        PreviousAlarmState = Disarmed;
        LastZoneAlarmed = 0;
        BatteryState = Battery_Disconnected;
        memset(RejectedPassword, '\0', USERPASSLENGTH);
        NTPTestResponse = NTP_TEST_DONE; // result of NTP test
        //initalise hardware
        // outputs
        STROBE_TRIS = 0;
        STROBE_IO = 0;
        EXT_SIREN_TRIS = 0;
        EXT_SIREN_IO = 0;
        INT_SIREN_TRIS = 0;
        INT_SIREN_IO = 0;
        SLA_CHARGER_TRIS = 0;
        SLA_CHARGER_IO = 0;
        // Analogue Demulplexer
        PLEXERA_0_TRIS = 0;
        PLEXERA_1_TRIS = 0;
        PLEXERA_2_TRIS = 0;
        PLEXERA_S_TRIS = 0;
        PLEXERA_0_IO = 0;
        PLEXERA_1_IO = 0;
        PLEXERA_2_IO = 0;
        //inputs
        SUPPLY_ACTIVE_TRIS = 1;
        // SMTP state machine, send out an email stating device has been restarted
        SMTPTaskList.CurentTask = 0;
        SMTPTaskList.FreePosition = 1;
        SMTPTaskList.Task[0].SMTP_SendType = SMTP_Reset;
        SMTPTaskList.Task[0].SMTP_State = SMTP_SM_InQ;
        SMPTTestResult = SMTP_TEST_DONE;
        for (iCount = 1; iCount < SMTPSMSIZE; iCount++) {
                SMTPTaskList.Task[iCount].SMTP_SendType = SMTP_Test;
                SMTPTaskList.Task[iCount].SMTP_State = SMTP_SM_Done;
        }
        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                ZoneConfig[iCount].IsTriggered = FALSE;
                ZoneConfig[iCount].IsArmed = FALSE;
                ZoneConfig[iCount].IsAlarmed = FALSE;
                ZoneConfig[iCount].IsChangeFlagged = FALSE;
                ZoneConfig[iCount].BounceDelay = 0;
                ZoneConfig[iCount].IsTampered = FALSE;
                ZoneConfig[iCount].IsIsolated = FALSE;  // should not continue state after a restart
        } // for
        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                AreaConfig[iCount].IsTriggered = FALSE;
                AreaConfig[iCount].IsArmed = FALSE;
                AreaConfig[iCount].IsAlarmed = FALSE;
                AreaConfig[iCount].IsChangeFlagged = FALSE;
                AreaConfig[iCount].IsIsolated = FALSE; // should not continue state after a restart
                AreaConfig[iCount].IsTampered = FALSE;
        } //for
        // xPL task buffer
        xPLTaskList.FreePosition = 0;
        xPLTaskList.CurentTask =0;
        // Set the TRIS flags to input for all of the A/D pins, page 331 chapter 21.0 of data sheet
        AN2_TRIS = 1;
        AN3_TRIS = 1;
        AN4_TRIS = 1;
        // Setup the A/D channels, page 329 of data sheet
        ADCON0 = 0b00001001;    // ADON = On(1), GO/DONE = Idle (0), AN1 selected (1000)
        ADCON1 = 0b00001010;    // upto AN4 enabled (1010), VCFG0 (Voltage ref) = Vdd/Vss (00)
        ADCON2 = 0b10111110;    // Fosc/64 (~21.0kHz) (110), 20TAD acquisition time (111), Right justify (0)
        // Do a calibration A/D conversion
        ADCON0bits.ADCAL = 1;
    ADCON0bits.GO = 1;
        while(ADCON0bits.GO);
        ADCON0bits.ADCAL = 0;
        //Queue reset email
        if (xPLConfig.SMTP_Active == TRUE)
                SMTPQueueEmail (SMTP_Reset);
        //Send gateway message
        SendGatewayReady();
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Security Schema initalised, Gateway message sent.\r\n");
#endif
        return ReturnResult;
}
void SchemaProcessUDPMsg (void)
Function SchemaProcessUDPMsg PreCondition: None Side Effects: Changes Armed / arming flags Overview: Called by xPL.c when ever a message is received. Here we determine what actions are needed in response to a message.
When changing the alarm state when there is no delay the arming timer is set to an expired value. This means the state change will not occur until the next task run occurs.
Parameters:
Delay
Returns:
None
Definition at line 1642 of file SecuritySystem.c.
References addxPLMessage(), AlarmState, AppConfig, Arm(), ArmAway(), ArmHome(), ArmLatchkey(), BOOL, Class_Config, Class_Security, ClearArmingFlags(), Command_arm, Command_armaway, Command_armhome, Command_armlatchkey, Command_bypass, Command_disarm, Command_enable, Command_isolate, Command_panic, Disarm(), Disarmed, DisplayIPValue(), EEDATASTART_CONFIG, EEDATASTART_XPL, xPLTasks::ErrorMessage, xPLConfigs::ExitDelay, FALSE, iCount, Panic(), putcUART, putrsUART, putsUART, Request_areainfo, Request_arealist, Request_areastat, Request_gateinfo, Request_gatestat, Request_zoneinfo, Request_zonelist, Request_zonestat, SaveKVP(), SecurityCommandText, SecurityRequestsText, SetArming(), xPLTaskLists::Task, TB_Bypass, TB_Enable, TB_Isolate, TB_SendAreaInfo, TB_SendAreaList, TB_SendAreaStat, TB_SendConfigCurrent, TB_SendConfigList, TB_SendError, TB_SendGateStat, TB_SendGatewayInfo, TB_SendZoneInfo, TB_SendZoneList, TB_SendZoneStat, To_Me, TRUE, Type_Basic, Type_Current, Type_List, Type_Request, Type_Response, UserID, USERNAMELENGTH, xPLConfigs::xPL_Heartbeat_Interval, xPLReceivedMessages::xPL_MsgDestination, xPLConfigs::xPL_My_Instance_ID, xPLReceivedMessages::xPL_SchemaClass, xPLReceivedMessages::xPL_SchemaTypes, xPLAuthenticate(), xPLFindArrayInKVP(), xPLMsgKey, xPLMsgValue, xPLReceivedMessage, and xPLSaveEEConfig().
Referenced by XPLProcessUDPMsg().
{
        int short TimeDelay = xPLConfig.ExitDelay;
        int TheMessageType, xPLTaskID;
        BOOL MessageIsCommand = FALSE;
        BOOL MessageIsRequest = FALSE;
        // Ensure the message is directed to me and its of the security class
        if ((xPLReceivedMessage.xPL_MsgDestination == To_Me ) && (xPLReceivedMessage.xPL_SchemaClass == Class_Security))  {
                // clear out any left over flags
                ClearArmingFlags();
                memset(UserID,'\0',USERNAMELENGTH);
                // We have to process all of the message before we can act on it as the message could be out of order. Open standards are not always standard
                while (SaveKVP(xPLMsgKey,xPLMsgValue )) {
                        if (memcmppgm2ram(xPLMsgKey, "user", 4)) {
                                if (!xPLAuthenticate(xPLMsgValue))
                                        return;
                        }
                        if (memcmppgm2ram(xPLMsgKey, (ROM void*)"area-list",9)) SetArming(xPLMsgValue, FALSE);
                        if (memcmppgm2ram(xPLMsgKey, (ROM void*)"zone-list",9)) SetArming(xPLMsgValue, TRUE);
                        if (memcmppgm2ram(xPLMsgKey, (ROM void*)"delay",5))  {
                                // Process delay value. If we receive text its might be the word 'default', either way we use the default value.
                                if( isdigit((unsigned char)xPLMsgValue[0] ) ==0 )
                                        TimeDelay = xPLConfig.ExitDelay;
                                else
                                        TimeDelay = atoi(xPLMsgValue);
                        }
                        if (memcmppgm2ram(xPLMsgKey, "command",7)) {
                                if (!xPLFindArrayInKVP(SecurityCommandText, 8, &TheMessageType, xPLMsgValue)) {
#if defined(DEBUG_UART)
                                        putrsUART((ROM char*)"#Note# command type not known\r\n");
#endif
                                }
                                else MessageIsCommand = TRUE;
                        }
                        if (memcmppgm2ram(xPLMsgKey, "request",7)) {
                                if (!xPLFindArrayInKVP(SecurityRequestsText, 8, &TheMessageType, xPLMsgValue)) {
#if defined(DEBUG_UART)
                                        putrsUART((ROM char*)"#Note# request type not known\r\n");
#endif
                                }
                                else MessageIsRequest = TRUE;
                        }
                } // while
                // ### Message Type BASIC
                if (xPLReceivedMessage.xPL_SchemaTypes == Type_Basic) {
                        if (MessageIsCommand) {
                                switch (TheMessageType) {
                                        case Command_arm: // Arm, needs area list or zone list
                                                Arm(TimeDelay);
                                                break;
                                        case Command_armhome:
                                                ArmHome(TimeDelay);
                                                break;
                                        case Command_armaway:
                                                ArmAway (TimeDelay);
                                                break;
                                        case Command_armlatchkey:
                                                ArmLatchkey (TimeDelay);
                                                break;
                                        case Command_disarm:
                                                // call Disarm and pass the userID
                                                Disarm();
                                                break;
                                        case Command_panic:
                                                Panic();
                                                break;
                                        case Command_isolate:
                                                addxPLMessage (TB_Isolate) ;
                                                break;
                                        case Command_bypass:
                                                addxPLMessage (TB_Bypass) ;
                                                break;
                                        case Command_enable:
                                                addxPLMessage (TB_Enable) ;
                                                break;
#if defined(DEBUG_UART)
                                        default:
                                                // Something has gone wrong!
                                                putrsUART((ROM char*)"#ERROR# Shit, something broke with Type_Basic when the message was received\r\n");
#endif
                                } // switch (TheMessageType)
                        } // MessageIsCommand
                } // xPLReceivedMessage.xPL_SchemaTypes == Type_Basic
                // ### Message Type REQUEST
                if (xPLReceivedMessage.xPL_SchemaTypes == Type_Request) {
                        if (MessageIsRequest) {
                                switch (TheMessageType) {
                                        case Request_gateinfo:
                                                // Send gateway infomation
                                                addxPLMessage (TB_SendGatewayInfo) ;
                                                break;
                                        case Request_zonelist:
                                                // Send zone list
                                                addxPLMessage (TB_SendZoneList) ;
                                                break;
                                        case Request_arealist:
                                                // Send area list
                                                addxPLMessage (TB_SendAreaList );
                                                break;
                                        case Request_zoneinfo:
                                                addxPLMessage (TB_SendZoneInfo );
                                                break;
                                        case Request_areainfo:
                                                addxPLMessage (TB_SendAreaInfo );
                                                break;
                                        case Request_gatestat:
                                                addxPLMessage (TB_SendGateStat);
                                                break;
                                        case Request_zonestat:
                                                addxPLMessage (TB_SendZoneStat);
                                                break;
                                        case Request_areastat:
                                                addxPLMessage (TB_SendAreaStat);
                                                break;
#if defined(DEBUG_UART)
                                                default:
                                                putrsUART((ROM char*)"#ERROR# Shit broken with Type_Request when msg rc'd\r\n");
#endif
                                } //switch (TheMessageType)
                        }// MessageIsRequest
                } // xPLReceivedMessage.xPL_SchemaTypes == Type_Request
        } // To_Me && Class_Security
        // #### Device Configuration ###
        if ((xPLReceivedMessage.xPL_MsgDestination == To_Me ) && (xPLReceivedMessage.xPL_SchemaClass == Class_Config))  {
                if(AlarmState != Disarmed) {
                        //      Note: do not allowing config changes when not in the disarmed state. A restart would make the system disarmed and or remove
                        //      parts of the alarm which would be a security risk.
                        xPLTaskID = addxPLMessage (TB_SendError);
                        xPLTaskList.Task[xPLTaskID].ErrorMessage = "Must be disarmed to update config";
                }
                else {
                        if (xPLReceivedMessage.xPL_SchemaTypes == Type_List)
                                addxPLMessage(TB_SendConfigList);
                        if (xPLReceivedMessage.xPL_SchemaTypes == Type_Current)
                                addxPLMessage (TB_SendConfigCurrent);
                        if (xPLReceivedMessage.xPL_SchemaTypes == Type_Response) {
                                while (SaveKVP(xPLMsgKey,xPLMsgValue )) {
                                        // Device name
                                        if (stricmppgm2ram(xPLMsgKey, (ROM char*) "newconf") ==0) {
                                                for (iCount =0; xPLMsgValue[iCount] != '\0' && iCount < sizeof(xPLConfig.xPL_My_Instance_ID); iCount++) {
                                                        if(xPLMsgValue[iCount] >= 'A' && xPLMsgValue[iCount] <= 'Z')
                                                                xPLMsgValue[iCount] -= 'A' - 'a'; //Convert to lower case
                                                        if((xPLMsgValue[iCount] > 'z') || (xPLMsgValue[iCount] < '0'))  xPLMsgValue[iCount]  = 0;
                                                }
                                                if (xPLMsgValue[0] != '\0') {
                                                        strcpy( xPLConfig.xPL_My_Instance_ID, xPLMsgValue);
                                                        xPLSaveEEConfig(&xPLConfig, EEDATASTART_XPL, sizeof(xPLConfig));
                                                }
#if defined(DEBUG_UART)
                                                putrsUART((ROM char*)"newconf =");
                                                putsUART(xPLConfig.xPL_My_Instance_ID);
                                                putrsUART((ROM char*)"\r\n");
#endif
                                        }
                                        if (stricmppgm2ram(xPLMsgKey, (ROM char*) "interval") ==0) {
                                                if(atoi(xPLMsgValue) > 1 )  {
                                                        xPLConfig.xPL_Heartbeat_Interval = atoi(xPLMsgValue);
                                                        xPLSaveEEConfig(&xPLConfig, EEDATASTART_XPL, sizeof(xPLConfig));
                                                }
#if defined(DEBUG_UART)
                                                putrsUART((ROM char*)"interval =");
                                                putcUART( '0' + xPLConfig.xPL_Heartbeat_Interval );
                                                putrsUART((ROM char*)"\r\n");
#endif
                                        }
                                        if (stricmppgm2ram(xPLMsgKey, (ROM char*) "ip") ==0) {
                                                if(StringToIPAddress(xPLMsgValue, &(AppConfig.MyIPAddr))) {
                                                        memcpy((void*)&(AppConfig.DefaultIPAddr), (void*)&(AppConfig.MyIPAddr), sizeof(IP_ADDR));
#if defined(DEBUG_UART)
                                                        putrsUART((ROM char*)"ip:");
                                                        DisplayIPValue(AppConfig.MyIPAddr);
                                                        putrsUART((ROM char*)"\r\n");
#endif
                                                        xPLSaveEEConfig(&AppConfig, EEDATASTART_CONFIG, sizeof(AppConfig));
                                                }
                                                else {
                                                        //
#if defined(DEBUG_UART)
                                                        putrsUART((ROM char*)"ip errored\r\n");
#endif
                                                }
                                        } //ip
                                        if (stricmppgm2ram(xPLMsgKey, ( ROM char *)"subnet") ==0)  {
                                                if(StringToIPAddress(xPLMsgValue, &(AppConfig.MyMask))) {
                                                        memcpy((void*)&(AppConfig.DefaultMask), (void*)&(AppConfig.MyMask), sizeof(IP_ADDR));
#if defined(DEBUG_UART)
                                                        putrsUART((ROM char*)"Subnet:");
                                                        DisplayIPValue(AppConfig.MyMask);
                                                        putrsUART((ROM char*)"\r\n");
#endif
                                                        xPLSaveEEConfig(&AppConfig, EEDATASTART_CONFIG, sizeof(AppConfig));
                                                }
                                                else {
                                                        //
#if defined(DEBUG_UART)
                                                        putrsUART((ROM char*)"Subnet errored\r\n");
#endif
                                                }
                                        }
                                } // while
#if defined(DEBUG_UART)
                                putrsUART((ROM char*)"\r\n\r\n Restart ##############");
#endif
                                Reset();
                        } //AlarmState != Disarmed
                }// if ((xPLReceivedMessage.xPL_MsgDestination == To_Me ) && (xPLReceivedMessage.xPL_SchemaClass == Class_Config))
        }// Config
} // SchemaProcessUDPMsg
BOOL SchemaTasks (void)
Function SchemaTasks PreCondition: None Side Effects: None Overview: General task manager for any implemented xPL Schema(s)
Todo:
add a timer that prevents the xPL task from blocking access to IOTasks();
Parameters:
None
Returns:
True if no task has ran
Definition at line 591 of file SecuritySystem.c.
References AREACOUNT, BatteryCheckTimer, BatteryTask(), BOOL, bypassZone(), xPLTaskLists::CurentTask, EnableZone(), xPLTasks::ErrorMessage, xPLTasks::FlaggedAreas, xPLTasks::FlaggedZones, xPLTaskLists::FreePosition, xPLTaskLists::GatewayChangedTimer, iCount, IOTasks(), AreaConfigs::IsChangeFlagged, IsolateZone(), xPLTasks::NewZoneState, SendACStat(), SendAlarmingMsg(), SendAreaInfo(), SendAreaList(), SendAreaStat(), SendAreaStateMsg(), SendArmed(), SendBatteryStat(), SendConfigList(), SendDisarm(), SendError(), SendGateStat(), SendGatewayChanged(), SendGatewayInfo(), SendZoneInfo(), SendZoneList(), SendZoneStat(), SMTP_Alarmed, SMTP_Arm, xPLConfigs::SMTP_ArmDisarm, SMTP_Disarm, SMTPQueueEmail(), StateChangeToArmFailed(), xPLTaskLists::Task, xPLTasks::TaskBuffered, xPLTasks::TaskState, TB_ArmFailed, TB_Bypass, TB_Enable, TB_Isolate, TB_Panic, TB_SendACStat, TB_SendAreaInfo, TB_SendAreaList, TB_SendAreaStat, TB_SendAreaStateMsg, TB_SendArmed, TB_SendBatteryStat, TB_SendConfigList, TB_SendDisarm, TB_SendError, TB_SendGateStat, TB_SendGatewayChanged, TB_SendGatewayInfo, TB_SendInvalidUser, TB_SendInvalidUserTimestamp, TB_SendZoneInfo, TB_SendZoneList, TB_SendZoneStat, TRUE, XPLBUFFERSIZE, and ZONECOUNT.
Referenced by XPLTasks().
                       {
        BOOL ReturnResult;
        int iCounter, DeviceSelected, CurrentTask;
        // If there are no tasks in queue check to see if the battery state should be checked
        if (xPLTaskList.FreePosition == xPLTaskList.CurentTask) {
                if (BatteryCheckTimer < TickGet()) {
                        BatteryCheckTimer = TickGet() + TICK_SECOND;
                        BatteryTask();
                }
        }
        // Is there a task to work on?
        if (xPLTaskList.FreePosition == xPLTaskList.CurentTask) {
                // as there are no messages to be sent, check the IOTasks to see if the state of the zones has changed
                ReturnResult = IOTasks();
                return ReturnResult;  // Returns is a message was sent by the IOTasks
                // todo add a timer that prevents the xPL task from blocking access to IOTasks();
        }
        // If the current task has not completed make sure it has the chance to run again.
        if (xPLTaskList.Task[xPLTaskList.CurentTask].TaskState == 0) {
                // updates the current Task, remember the current task will end up being the last task processed once this has run
                if (xPLTaskList.CurentTask < (XPLBUFFERSIZE-1))
                        xPLTaskList.CurentTask++;
                else if(xPLTaskList.CurentTask >= (XPLBUFFERSIZE-1))
                        xPLTaskList.CurentTask =0;
        }
        CurrentTask = xPLTaskList.CurentTask;
        // populate IsChangeFlagged from the zone array for the task to be processed
        for(iCounter =0; iCounter < ZONECOUNT; iCounter++)
                 ZoneConfig[iCounter].IsChangeFlagged = xPLTaskList.Task[xPLTaskList.CurentTask].FlaggedZones[iCounter];
        // populate IsChangeFlagged from the area array for the task to be processed
                for(iCounter =0; iCounter <= AREACOUNT; iCounter++)
                        AreaConfig[iCounter].IsChangeFlagged = xPLTaskList.Task[xPLTaskList.CurentTask].FlaggedAreas[iCounter];
        switch (xPLTaskList.Task[xPLTaskList.CurentTask].TaskBuffered) {
                case TB_SendConfigList:
                        SendConfigList(); //very simple
                        break;
                case TB_ArmFailed:
                        StateChangeToArmFailed(); // needs zones or areas populated
                        break;
                case TB_SendArmed:
                        SendArmed(); // extracts data from the zones & area directly
                        if(xPLConfig.SMTP_ArmDisarm == TRUE)
                                SMTPQueueEmail (SMTP_Arm); // queue an email notification
                        break;
                case TB_SendDisarm:
                        SendDisarm();
                        if(xPLConfig.SMTP_ArmDisarm == TRUE)
                                SMTPQueueEmail (SMTP_Disarm);
                        break;
                case TB_Panic:
                        SendAlarmingMsg(99);
                        SMTPQueueEmail (SMTP_Alarmed);
                        break;
                case TB_SendGatewayInfo:
                        SendGatewayInfo();
                        break;
                case TB_SendZoneList:
                        SendZoneList();
                        break;
                case TB_SendAreaList:
                        SendAreaList();
                        break;
                case TB_SendGateStat:
                        SendGateStat();
                        break;
                case TB_SendAreaStat:
                        for(iCounter =0; iCounter < AREACOUNT; iCounter++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedAreas[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        SendAreaStat (DeviceSelected);
                        break;
                case TB_SendZoneStat:
                        for(iCounter =0; iCounter < ZONECOUNT; iCounter++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        SendZoneStat (DeviceSelected);
                        break;
                case TB_SendZoneInfo:
                        for (iCount = 0; iCount < ZONECOUNT; iCount++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        SendZoneInfo(DeviceSelected);
                        break;
                case TB_SendAreaInfo:
                        for(iCounter =0; iCounter < AREACOUNT; iCounter++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedAreas[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        SendAreaInfo(DeviceSelected);
                        break;
                case TB_Isolate:
                        for (iCount = 0; iCount < ZONECOUNT; iCount++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        IsolateZone(DeviceSelected);
                        break;
                case TB_Bypass:
                        for (iCount = 0; iCount < ZONECOUNT; iCount++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        bypassZone(DeviceSelected);
                        break;
                case TB_Enable:
                        for (iCount = 0; iCount < ZONECOUNT; iCount++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        EnableZone(DeviceSelected);
                        break;
                case TB_SendAreaStateMsg:
                        for (iCount = 0; iCount < ZONECOUNT; iCount++)
                                if (xPLTaskList.Task[CurrentTask].FlaggedZones[iCounter] == 1)
                                        DeviceSelected = iCounter;
                        xPLTaskList.Task[CurrentTask].TaskState = SendAreaStateMsg (xPLTaskList.Task[CurrentTask].NewZoneState, DeviceSelected, xPLTaskList.Task[CurrentTask].TaskState);
                        break;
                case TB_SendInvalidUser:
                        SendError( (ROM char *)"user invalid");
                        break;
                case TB_SendInvalidUserTimestamp:
                        SendError( (ROM char *)"Timestamp out of range. Check system time");
                        break;
                case TB_SendGatewayChanged:
                        SendGatewayChanged();
                        xPLTaskList.GatewayChangedTimer = 0;
                        break;
                case TB_SendError:
                        SendError(xPLTaskList.Task[CurrentTask].ErrorMessage);
                        break;
                case TB_SendBatteryStat:
                        SendBatteryStat();
                        break;
                case TB_SendACStat:
                        SendACStat();
                        break;
        } // switch
        return ReturnResult;
} //SchemaTasks
void SetArming (char * TheValue, BOOL isZone)
Function SetArmingZone PreCondition: None Side Effects: Sets arming flags for zones Overview: Sets the arming flags for the zones based on values in the KVP
Parameters:
Value from xPL message, BOOL is zone - False is Area
Returns:
None
Definition at line 1537 of file SecuritySystem.c.
References AREACOUNT, i2Count, iCount, AreaConfigs::IsChangeFlagged, ZoneConfigs::IsChangeFlagged, TRUE, xPLMSGVALUELENGTH, and ZONECOUNT.
Referenced by SchemaProcessUDPMsg().
{
        int DeviceID;
        char TempBuffer[3];
        //if 'all' then set all zones to arming
        if (strncmppgm2ram(TheValue,"all",3)) {
                if (isZone) {
                        // Loop though all of the zones
                        for (iCount = 0; iCount < ZONECOUNT; iCount++) {
                                if ((!ZoneConfig[iCount].IsIsolated) && (!ZoneConfig[iCount].IsBypassed)) {
                                        ZoneConfig[iCount].IsChangeFlagged = TRUE;
                                }
                        } // for
                } // isZone
                else {
                        // Loop though all of the Area's
                        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                                if ((!AreaConfig[iCount].IsIsolated) && (!AreaConfig[iCount].IsBypassed)) {
                                        AreaConfig[iCount].IsChangeFlagged = TRUE;
                                }
                        } // for
                }// !isZone
        }// if (all)
        else {
                // looking for digits seperated by a commar and terminated by new line eg (01, 02 ,3,4,12\n)
                memset(TempBuffer,'\0', 3);
                for (iCount = 0, i2Count =0;iCount < xPLMSGVALUELENGTH; iCount++) {
                        if (TheValue[iCount] == ' ') //ignore spaces
                                if ((i2Count ==0) && (TheValue[iCount] == '0')) //ignore leading zeros
                                        if ((TheValue[iCount] == ',') || (TheValue[iCount] == '\n')) {
                                                //make sure we have data first
                                                if (!i2Count == 0) {
                                                        DeviceID = atoi(TempBuffer);
                                                        // ensure that the zone is valid, if so arm it
                                                        if (isZone) {
                                                                if ((DeviceID < ZONECOUNT) && (DeviceID != 0)) ZoneConfig[iCount].IsChangeFlagged = TRUE;
                                                        }
                                                        if (!isZone) {
                                                                if ((DeviceID < AREACOUNT) && (DeviceID != 0)) AreaConfig[iCount].IsChangeFlagged = TRUE;
                                                        }
                                                        if (TheValue[iCount] == '\n') break; // signals the end of the line
                                                        memset(TempBuffer,'\0', 3);
                                                }//(!i2Count == 0)
                                        }// ((TheValue[iCount] == ',') || (TheValue[iCount] == '\n'))
                                        else {
                                                TempBuffer[i2Count] = TheValue[iCount];
                                                i2Count++;
                                        }
                }// for
        } // else
} // SetArmingZone
void SetArmingArea (char * TheValue)
Function SetArmingArea PreCondition: None Side Effects: Sets arming flags for areas Overview: Sets the arming flags for the area based on values in the KVP
Parameters:
Value from xPL message
Returns:
None
Definition at line 1521 of file SecuritySystem.c.
{
}
void StateChangeToAlarmed (void) [static]
Function StateChangeToAlarmed PreCondition: None Side Effects: None Overview: Used to change the alarmed state
Parameters:
None
Returns:
IO changes
Definition at line 993 of file SecuritySystem.c.
References Alarmed, Alarmed24, Alarming, Alarming24, AlarmingTimer, AlarmState, EXT_SIREN_IO, INT_SIREN_IO, putrsUART, and SirenTimer.
Referenced by TaskAlarming().
{
        // Tell the debugger
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"State changed to Alarmed, siren and strobe off\r\n");
#endif
        //Clear timers
        AlarmingTimer = 0;
        SirenTimer = 0;
        //Stop sirens
        EXT_SIREN_IO = 0;
        INT_SIREN_IO = 0;
        //Change internal state to alarmed
        if (AlarmState == Alarming24) AlarmState = Alarmed24;
        if (AlarmState == Alarming) AlarmState = Alarmed;
}
void StateChangeToAlarming (int ZoneID) [static]
Used to change the alarm state, sends out required messages and chages any IO lines such as siren and strobe
Parameters:
ZoneID
Returns:
IO changes
Definition at line 916 of file SecuritySystem.c.
References Alarming, Alarming24, xPLConfigs::Alarming24Duration, xPLConfigs::AlarmingDuration, AlarmingTimer, AlarmState, AREACOUNT, EntryTimer, ExitTimer, FALSE, INT_SIREN_IO, AreaConfigs::IsAlarmed, ZoneConfigs::IsAlarmed, isZoneMemberOfArea(), LastZoneAlarmed, putrsUART, SendAlarmingMsg(), Silent, xPLConfigs::SirenDelay, xPLConfigs::SirenDelay24h, SirenTimer, SMTP_Alarmed, xPLConfigs::SMTP_OnlyInitalAlarm, SMTPQueueEmail(), AreaConfigs::State, ZoneConfigs::State, StateAlarm, StateBypass, StateIsolate, STROBE_IO, TRUE, and TwentyFourHour.
Referenced by IOTasks().
{
        int AreaCount;
        // Tell the dubugger
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"State change to alarming\r\n");
#endif
        //Ensure entry and exit timers are cleared
        EntryTimer = 0;
        ExitTimer = 0;
        // Start the strobe and internal siren
        if (ZoneConfig[ZoneID].ZoneType != Silent) {
                STROBE_IO = 1;
                INT_SIREN_IO = 1;
        }
        // update the zone state
        ZoneConfig[ZoneID].IsAlarmed = TRUE;
        ZoneConfig[ZoneID].State = StateAlarm;
        // Update the area state
        for (AreaCount = 0; AreaCount < AREACOUNT; AreaCount++) {
                if (isZoneMemberOfArea(ZoneID, AreaCount) == TRUE)
                        AreaConfig[AreaCount].IsAlarmed = TRUE;
                        // if area is not isolted or bypassed
                        if ((AreaConfig[AreaCount].State != StateBypass) && (AreaConfig[AreaCount].State != StateIsolate))
                                AreaConfig[AreaCount].State = StateAlarm;
        }
        //Queue email
        LastZoneAlarmed = ZoneID;
        if (xPLConfig.SMTP_OnlyInitalAlarm == FALSE)
                SMTPQueueEmail (SMTP_Alarmed);
        // Dont want to reset the alarm timers each time something is triggered
        if ((AlarmState !=Alarming24) &&  (AlarmState !=Alarming))  {
                //Queue email email
                if (xPLConfig.SMTP_OnlyInitalAlarm == TRUE)
                        SMTPQueueEmail (SMTP_Alarmed);
                if (ZoneConfig[ZoneID].ZoneType != TwentyFourHour) {
                        AlarmState = Alarming;//Change the current state to alarming
                        SirenTimer = TickGet() + (TICK_SECOND * xPLConfig.SirenDelay); //check to see if external siren should be activated
                        AlarmingTimer =  TickGet() + (TICK_SECOND * xPLConfig.AlarmingDuration);
                }
                else {
                        AlarmState = Alarming24; //Change the current state to alarming
                        SirenTimer = TickGet() + (TICK_SECOND * xPLConfig.SirenDelay24h);
                        AlarmingTimer =  TickGet() + (TICK_SECOND * xPLConfig.Alarming24Duration);
                }
        } // !=Alarming
        // If the zone type is silent then do not allow the siren timer
        if (ZoneConfig[ZoneID].ZoneType == Silent)
                SirenTimer = 0;
        // Send the alarming message
        SendAlarmingMsg(ZoneID);
}
void StateChangeToArm (BOOL isLatchKey) [static]
Function StateChangeToArm PreCondition: ExitTimer must be set Side Effects: Changes Armed / arming flags and state Overview: Perform a test on all zones to ensure it is in a good state to be armed. If not it will generate an xPL error message. Converts all of the arming flags into Armed flags, then clears arming flags and sends the armed message
Parameters:
None
Returns:
None
Definition at line 1296 of file SecuritySystem.c.
References addxPLMessage(), AlarmState, AREACOUNT, Armed, Armed_LatchKey, ArmingZoneState(), BOOL, FALSE, xPLTasks::FlaggedZones, i2Count, iCount, ZoneConfigs::IsArmed, AreaConfigs::IsChangeFlagged, isZoneMemberOfArea(), putrsUART, StateNormal, xPLTaskLists::Task, TB_ArmFailed, TB_SendArmed, TRUE, and ZONECOUNT.
Referenced by Arm(), ArmAway(), ArmHome(), and ArmLatchkey().
{
        BOOL isAllZonesArmed, OneOrMoreZones, ArmFailed;
        int Counter, TaskNumber, ZoneCounter;
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"State change to arm called\r\n");
#endif
        // determine if an arming zone is triggered, if so cancel the action
        ArmFailed = FALSE;
        for (Counter=0;Counter <= ZONECOUNT;Counter++) {
                if (ArmingZoneState(Counter) != StateNormal) {  // add entry & exit zones here
                        // The test has failed
                        if (ArmFailed == FALSE) {
                                // This is the first failed zone
                                TaskNumber = addxPLMessage (TB_ArmFailed); // create the task
                                for (ZoneCounter=0;ZoneCounter <= ZONECOUNT; ZoneCounter++) // clear out the zone list
                                        xPLTaskList.Task[TaskNumber].FlaggedZones[ZoneCounter] = 0;
                                ArmFailed = TRUE;
                        }
                        // flag this zone as errored
                        xPLTaskList.Task[TaskNumber].FlaggedZones[Counter] = 1;
                        }
        }
        if (ArmFailed) {
        #if defined(DEBUG_UART)
                putrsUART((ROM char*)"Arm failed as a zone is incorrect\r\n");
        #endif
                goto Exit_Here; // do not arm the system
        }
        //Cycle through all of the zones
        for (iCount =0; iCount < ZONECOUNT; iCount++) {
                //skip the bypassed or disabled. Arm anything that has the arming flag
                if ((!ZoneConfig[iCount].IsIsolated) && (!ZoneConfig[iCount].IsBypassed))
                {
                        if(ZoneConfig[iCount].IsChangeFlagged) ZoneConfig[iCount].IsArmed = TRUE;
                }
        }// for loop
        // cycle though the area's, if all the zones in an area are armed, make the area armed as well
        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                if ( (!AreaConfig[iCount].IsIsolated) && (!AreaConfig[iCount].IsBypassed) ) {
                        isAllZonesArmed = TRUE;
                        OneOrMoreZones = FALSE;
                        for (i2Count = 0; i2Count < ZONECOUNT; i2Count++) {
                                //is this zone a member?
                                if (isZoneMemberOfArea(iCount, i2Count) == TRUE) {
                                        // ensure it is not disable before arming
                                        if ((!ZoneConfig[i2Count].IsIsolated) && (!ZoneConfig[i2Count].IsBypassed)) {
                                                if (ZoneConfig[i2Count].IsArmed == TRUE) {
                                                        ZoneConfig[i2Count].IsArmed = TRUE;
                                                        OneOrMoreZones = TRUE;
                                                }
                                                else isAllZonesArmed = FALSE;
                                        } // Zone not isolated or bypassed
                                }// IsMemberofArea
                        } // for i2Count
                        if (OneOrMoreZones && isAllZonesArmed)
                                AreaConfig[iCount].IsChangeFlagged = TRUE;
                }// IsChangeFlagged
        }// for iCount
        //Cycle through all areas, if one is arming enable all zones in the area
        for (iCount = 0; iCount < AREACOUNT; iCount++) {
                if ((AreaConfig[iCount].IsChangeFlagged) && ((!AreaConfig[iCount].IsIsolated) && (!AreaConfig[iCount].IsBypassed)) ) {
                        for (i2Count = 0; i2Count < ZONECOUNT; i2Count++) {
                                //is this zone a member?
                                if (isZoneMemberOfArea(iCount, i2Count) == TRUE) {
                                        // ensure it is not disable before arming
                                        if ((!ZoneConfig[i2Count].IsIsolated) && (!ZoneConfig[i2Count].IsBypassed)) ZoneConfig[i2Count].IsArmed = TRUE;
                                }// IsMemberofArea
                        } // for i2Count
                }// IsChangeFlagged
        }// for iCount
        // Change the state
        if (isLatchKey) AlarmState = Armed_LatchKey;
        else AlarmState = Armed;
        // sends message and clears flags
        addxPLMessage(TB_SendArmed);
Exit_Here:
        // Greetings human
        Counter = 0;
}
void StateChangeToArmFailed (void) [static]
Function StateChangeToArmFailed PreCondition: None Side Effects: Changes arming flags Overview: This is called when a Arming (any type) action fails. It will clear the arming flags
Parameters:
None
Returns:
None
Definition at line 1411 of file SecuritySystem.c.
References BOOL, Class_Security, FALSE, iCount, putrsUART, TRUE, Type_Gateway, xPL_STATUS, xPLMsgKey, XPLSendHeader(), XPLSocket, and ZONECOUNT.
Referenced by SchemaTasks().
{
        BOOL FirstZone = TRUE;
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"State change to arm failed\r\n");
#endif
        //Check if we have a MAC transmit port, if not then shit yourself
        if (!UDPIsPutReady(XPLSocket)) {
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"#ERROR# ArmFailed, no MAC transmit port\r\n");
#endif
        }
        else {
                //Generate xPL head with type security.gateway
                XPLSendHeader(xPL_STATUS, TRUE,Class_Security,Type_Gateway);
                UDPPutROMString((ROM BYTE*) "event=error\nzone-list=");
                //Scan all zones, list those that are triggered and of status arming
                for (iCount =0; iCount < ZONECOUNT; iCount++) {
                        if ((ZoneConfig[iCount].IsTriggered) && (ZoneConfig[iCount].IsChangeFlagged))
{
                                if (FirstZone == FALSE) UDPPut(',');
                                itoa(iCount, xPLMsgKey);
                                UDPPutArray(xPLMsgKey,strlen(xPLMsgKey));
                                FirstZone = FALSE;
                        }
                }
                UDPPutROMString((ROM BYTE*) "\nerror=Arm fail as zone tripped");
                UDPPutROMString((ROM BYTE*) "\n}\n");
                // Now transmit it.
                UDPFlush();
        }
}
void TaskAlarmed (void) [static]
Function TaskAlarmed PreCondition: None Side Effects: None Overview: Used to change the IO outputs while in the alarmed state
Parameters:
None
Returns:
IO changes
Definition at line 1074 of file SecuritySystem.c.
Referenced by IOTasks().
{
        //nothing to do here
}
void TaskAlarming (void) [static]
Function TaskAlarming PreCondition: None Side Effects: None Overview: Used to change the IO outputs while in the alarming state
Parameters:
None
Returns:
IO changes
Definition at line 1025 of file SecuritySystem.c.
References AlarmingTimer, EXT_SIREN_IO, INT_SIREN_IO, putrsUART, putsUART, SirenTimer, and StateChangeToAlarmed().
Referenced by IOTasks().
{
        static int DebugTimer; // Only prints updates on new second
        int SecondsLeft;
        char DebugOut[6];
        // Time delay before activating the external siren
        if ((SirenTimer != (unsigned) 0) && (TickGet() > SirenTimer))  SirenTimer = 0;
        //Set sirens
        if (SirenTimer == (unsigned) 0) {
                EXT_SIREN_IO = 1;
                INT_SIREN_IO = 1;
        }
        // has the siren gone on for long enough?
        if (TickGet() > AlarmingTimer) {
                StateChangeToAlarmed();
                DebugTimer = 0;
                AlarmingTimer = 0;
        }
        // Debug output
#if defined(DEBUG_UART)
        SecondsLeft = (AlarmingTimer - TickGet()) / TICK_SECOND;
        if (DebugTimer != SecondsLeft) {
                DebugTimer = SecondsLeft;
#if defined(DEBUG_UART)
                putrsUART((ROM char*)"Alarming count down: ");
                uitoa(DebugTimer,  DebugOut);
                putsUART(DebugOut);
                putrsUART((ROM char*)"\r\n");
#endif
        }
#endif
}
void xPLFactoryRestart (void)
Function xPLFactoryRestart PreCondition: None Side Effects: Kills the starting character of the EEProm config data Overview: Performs a factory restart of the device, clearing everything
Parameters:
None
Returns:
None
Definition at line 515 of file SecuritySystem.c.
References Class_HBeat, EEDATASTART_AREA, EEDATASTART_CONFIG, EEDATASTART_XPL, EEDATASTART_ZONE, iCount, MPFS_RESERVE_BLOCK, putrsUART, TRUE, Type_END, xPL_STATUS, XPLSendHeader(), and XPLSocket.
{
        char TempVal[9];
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"##### Factory restart in progress #####\r\n");
#endif
        // I dont think this will work as we do not call the StackTasks to send the message
        // if we have a good socket send the message, if not then do not bother
        if (UDPIsPutReady(XPLSocket)) {
                // Send header
                XPLSendHeader(xPL_STATUS, TRUE,Class_HBeat,Type_END);
                UDPPutROMString((ROM BYTE*) "interval=0\n}\n");
                // Now transmit it.
                UDPFlush();
        }
    XEEBeginWrite(EEDATASTART_ZONE); // Zone config
    XEEWrite(0x00); // 0x00 will cause the xPLLoadEEConfig function to fail and revert to default settings.
    XEEEndWrite();
    XEEBeginWrite(EEDATASTART_AREA); // area config
    XEEWrite(0x00); // 0x00 will cause the xPLLoadEEConfig function to fail and revert to default settings.
    XEEEndWrite();
    XEEBeginWrite(EEDATASTART_XPL); // device config
    XEEWrite(0x00); // 0x00 will cause the xPLLoadEEConfig function to fail and revert to default settings.
    XEEEndWrite();
    XEEBeginWrite(EEDATASTART_CONFIG); // IP address, this is a part of the TCIP stack
    XEEWrite(0x00); // 0x00 will cause the xPLLoadEEConfig function to fail and revert to default settings.
    XEEEndWrite();
    while(XEEIsBusy());
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"Clearing config data\r\n");
#endif
        // Blank everything
    for (iCount = EEDATASTART_XPL; iCount < (MPFS_RESERVE_BLOCK - 2); iCount++) {
                XEEBeginWrite(iCount);
                XEEWrite('.');
        XEEEndWrite();
                while(XEEIsBusy());
    }
#if defined(DEBUG_UART)
        putrsUART((ROM char*)"All config data has been deleted. \r\n");
        putrsUART((ROM char*)"Restarting device.............\r\n");
#endif
    // perform a Hardware restart
        Reset();
}
Variable Documentation
TICK AlarmingTimer
Times how long the alarm will sound for.
Definition at line 29 of file SecuritySystem.c.
Referenced by Panic(), StateChangeToAlarmed(), StateChangeToAlarming(), and TaskAlarming().
Alarm_States AlarmState
Reflects the state of the alarm.
D E C L A R A T I O N S
Definition at line 17 of file SecuritySystem.c.
Referenced by Disarm(), HTTPExecuteGet(), HTTPPrint_AlarmState(), IOTasks(), Panic(), SchemaInit(), SchemaProcessUDPMsg(), SendGateStat(), StateChangeToAlarmed(), StateChangeToAlarming(), and StateChangeToArm().
ROM char* AlarmTypesText[]
Initial value:
{
        "buglary",
        "fire",
        "flood",
        "gas",
        "silent",
        "duress",
        "other",
        ""
}
determines the text outputed in the xPL message for each of the alarm types
Definition at line 44 of file SecuritySystem.c.
Referenced by HTTPPrint_AlarmTypeList(), SendAlarmingMsg(), SendAreaStat(), SendGateStat(), SendZoneInfo(), and SendZoneStat().
AreaConfigs AreaConfig[AREACOUNT]
Stores each Area configuration information.
Definition at line 149 of file SecuritySystem.c.
Referenced by addxPLMessage(), HTTPExecuteGet(), HTTPPrint_AreasAlarmed(), HTTPPrint_AreasAlarmType(), HTTPPrint_AreasArmed(), HTTPPrint_AreasBypassed(), HTTPPrint_AreasIsolated(), HTTPPrint_AreasTriggered(), HTTPPrint_AreaTampered(), IsZoneTriggered(), SendAreaStat(), SendAreaStateMsg(), and SendArmed().
TICK BatteryCheckTimer = 0
Timer checking the battery status.
Definition at line 33 of file SecuritySystem.c.
Referenced by SchemaTasks().
DWORD dwLastUpdateTick
Tick count of last update.
Definition at line 134 of file CustomSNTP.c.
Referenced by HTTPPrint_NTPLastUpdate(), SchemaInit(), SNTPClient(), and SNTPGetUTCSeconds().
TICK EntryTimer
Zone Entery timer.
Definition at line 21 of file SecuritySystem.c.
Referenced by Disarm(), IOTasks(), Panic(), SchemaInit(), and StateChangeToAlarming().
TICK ExitTimer
Exit timer - 0 means off.
Definition at line 25 of file SecuritySystem.c.
Referenced by Arm(), ArmAway(), ArmHome(), ArmLatchkey(), Disarm(), IOTasks(), Panic(), SchemaInit(), and StateChangeToAlarming().
int i2Count
Definition at line 35 of file SecuritySystem.c.
Referenced by Arm(), IsZoneTriggered(), SendAreaStat(), SetArming(), SMTPTaskProcess(), and StateChangeToArm().
int iCount
Counters that are used in a number of places, centraly defined to reduce memory use.
Definition at line 35 of file SecuritySystem.c.
Referenced by Arm(), ArmAway(), ArmHome(), ArmLatchkey(), Authenticate(), bypassArea(), ClearArmingFlags(), DecodeIntFromGET(), Disarm(), EnableArea(), HTTPCheckAuth(), HTTPExecuteGet(), HTTPPrint_AlarmTypeList(), HTTPPrint_AreaDesc(), HTTPPrint_AreasAlarmed(), HTTPPrint_AreasAlarmType(), HTTPPrint_AreasArmed(), HTTPPrint_AreasBypassed(), HTTPPrint_AreasIsolated(), HTTPPrint_AreasTriggered(), HTTPPrint_AreaTampered(), HTTPPrint_TypeList(), HTTPPrint_ZoneDesc(), HTTPPrint_ZonesAlarmed(), HTTPPrint_ZonesAlarmType(), HTTPPrint_ZonesAreaList(), HTTPPrint_ZonesArmed(), HTTPPrint_ZonesBypassed(), HTTPPrint_ZonesEntry(), HTTPPrint_ZonesIsolated(), HTTPPrint_ZonesNO(), HTTPPrint_ZonesTampered(), HTTPPrint_ZonesTriggered(), HTTPPrint_ZonesType(), IsolateArea(), IsZoneTriggered(), LoadDefaultConfig(), ModifyUser(), SaveDeviceDescription(), SaveKVP(), SaveUserNameEEdata(), SaveUserPasswordEEdata(), SchemaInit(), SchemaProcessUDPMsg(), SchemaTasks(), SendAlarmingMsg(), SendAreaInfo(), SendAreaList(), SendAreaStat(), SendArmed(), SendConfigCurrent(), SendGateStat(), SendZoneInfo(), SendZoneList(), SetArming(), StateChangeToArm(), StateChangeToArmFailed(), xPLAuthenticate(), xPLFactoryRestart(), xPLFindArrayInKVP(), xPLProcess_MsgField(), xPLProcessMsgCompair(), xPLSaveEEConfig(), XPLSendHeader(), and XPLSendHeartBeat().
unsigned int LastZoneAlarmed
The last zone to change to alarmed state. used in SMTP.c.
Definition at line 39 of file SecuritySystem.c.
Referenced by SchemaInit(), SendGateStat(), SMTPTaskProcess(), and StateChangeToAlarming().
TICK NextZoneCheckDelay
Delay used so we are not always checking the status of the zones.
Definition at line 27 of file SecuritySystem.c.
Referenced by IOTasks(), and SchemaInit().
Alarm_States PreviousAlarmState
The previous state of the alarm system, used when state change fails.
Definition at line 19 of file SecuritySystem.c.
Referenced by Disarm(), and SchemaInit().
ROM char* SecurityCommandText[] [static]
Initial value:
{
        "arm",
        "arm-home",
        "arm-away",
        "arm-latchkey",
        "disarm",
        "panic",
        "isolate",
        "bypass",
        "enable"
}
Security command Types.
Definition at line 68 of file SecuritySystem.c.
Referenced by SchemaProcessUDPMsg().
ROM char* SecurityRequestsText[] [static]
Initial value:
{
        "gateinfo",
        "zonelist",
        "arealist",
        "zoneinfo",
        "areainfo",
        "gatestat",
        "zonestat",
        "areastat"
}
xPL feild values for the different security requests
Definition at line 109 of file SecuritySystem.c.
Referenced by SchemaProcessUDPMsg().
TICK SirenTimer
Times the delay before acivating the external siren.
Definition at line 31 of file SecuritySystem.c.
Referenced by Panic(), StateChangeToAlarmed(), StateChangeToAlarming(), and TaskAlarming().
TICK TriggeredEntryZone
Triggered Entery Zone that set off the timer.
Definition at line 23 of file SecuritySystem.c.
Referenced by IOTasks(), and SchemaInit().
char UserID[USERNAMELENGTH]
Name of user.
Definition at line 37 of file SecuritySystem.c.
Referenced by Authenticate(), ModifyUser(), SchemaProcessUDPMsg(), SendArmed(), SendDisarm(), and SMTPTaskProcess().
xPLConfigs xPLConfig
Configuration entries.
Definition at line 136 of file SecuritySystem.c.
Referenced by HTTPExecuteGet(), HTTPPostSMTPConfig(), HTTPPrint_AES_Active(), HTTPPrint_Alarming24Duration(), HTTPPrint_AlarmingDuration(), HTTPPrint_EntryDelay(), HTTPPrint_ExitDelay(), HTTPPrint_HeartBeatTime(), HTTPPrint_InstanceName(), HTTPPrint_NTPServer(), HTTPPrint_SirenDelay(), HTTPPrint_SirenDelay24h(), HTTPPrint_SMTP_Active(), HTTPPrint_SMTP_ArmDisarm(), HTTPPrint_SMTP_OnlyInitalAlarm(), HTTPPrint_SMTP_Password(), HTTPPrint_SMTP_Port(), HTTPPrint_SMTP_Server(), HTTPPrint_SMTP_To(), HTTPPrint_SMTP_User(), SendConfigCurrent(), SMTPQueueEmail(), SMTPTaskProcess(), SNTPClient(), xPLAuthenticate(), XPLHeartBeatTiming(), xPLInit(), XPLProcessUDPMsgHeader(), XPLSendHeader(), and XPLSendHeartBeat().
xPLTaskLists xPLTaskList
The Task buffer for sending xPL messages.
Definition at line 128 of file SecuritySystem.c.
Referenced by addxPLMessage(), and HTTPExecuteGet().
ZoneConfigs ZoneConfig[ZONECOUNT]
Stores each Zones configuration information.
Definition at line 143 of file SecuritySystem.c.
Referenced by addxPLMessage(), CheckEOL(), HTTPExecuteGet(), HTTPPrint_ZonesAlarmed(), HTTPPrint_ZonesAlarmType(), HTTPPrint_ZonesAreaList(), HTTPPrint_ZonesArmed(), HTTPPrint_ZonesBypassed(), HTTPPrint_ZonesEntry(), HTTPPrint_ZonesIsolated(), HTTPPrint_ZonesNO(), HTTPPrint_ZonesTampered(), HTTPPrint_ZonesTriggered(), HTTPPrint_ZonesType(), IsZoneTriggered(), SendAlarmingMsg(), SendArmed(), SendGateStat(), SendZoneInfo(), and SendZoneStat().
ROM char* ZoneTypesText[]
Initial value:
{
        "perimeter",
        "interior",
        "24hour",
        ""
}
determines the text outputed in the xpl message for each of the zone types
Definition at line 58 of file SecuritySystem.c.
Referenced by HTTPPrint_TypeList(), and SendZoneInfo().